(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.Symbol46 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35475B").s().p("AUTEQQgYgUAAgoIAAAAIAwAAQAAAXAIAKQAKAKARAAQAQAAAHgIQAIgJAAgOQAAgOgHgJQgIgJgTgIQgmgMgSgRQgUgRAAgfQABgeAVgSQAVgTAjAAQAiAAAWAUQAWAUgBAiIAAABIguAAQAAgSgJgLQgJgKgPAAQgNAAgIAKQgHAIAAAPQAAAMAJAHQAJAJAUAJQAjAMASASQASARABAfQgBAfgVASQgVASgkAAQgjAAgYgTgAL6ELQgZgWAAgrIAAifIAvAAIAACfQAAAZALAOQAKANASAAQASAAAKgNQALgNAAgaIAAifIAvAAIAACfQAAArgYAWQgXAYgnAAQgnAAgWgYgAI7EQQgYgUAAgoIAAAAIAvAAQAAAXAJAKQAJAKASAAQAPAAAJgIQAHgJABgOQAAgOgIgJQgIgJgUgIQgkgMgUgRQgSgRAAgfQAAgeAVgSQAWgTAhAAQAkAAAVAUQAXAUgCAiIAAABIguAAQAAgSgJgLQgIgKgQAAQgNAAgIAKQgIAIABAPQgBAMAJAHQAJAJAVAJQAjAMASASQASARAAAfQAAAfgVASQgVASgkAAQgjAAgYgTgAjjELQgYgWAAgrIAAifIAvAAIAACfQABAZAJAOQALANASAAQASAAALgNQAKgNAAgaIAAifIAuAAIAACfQABArgXAWQgYAYgnAAQgmAAgYgYgAzFELQgZgZAAgqIAAhFQAAgqAZgYQAYgZAoAAQApAAAXAZQAZAYAAAqIAABFQAAAqgZAZQgXAYgpAAQgoAAgYgYgAyjBbQgMAOAAAaIAABFQAAAaAMAOQAKAOAUAAQAVAAALgOQALgOgBgaIAAhFQABgagLgOQgLgOgVAAQgUAAgKAOgASBEgIAAjPIg3AAIAAgmIChAAIAAAmIg7AAIAADPgAOxEgIAAj1IAvAAIAADQIBaAAIAAAlgAGDEgIAAj1ICIAAIAAAmIhZAAIAAA9IBLAAIAAAmIhLAAIAABHIBZAAIAAAlgAE4EgQgGgGgBgMQgCgMAAgMIAAgSQgBgRgHgLQgIgKgPAAIgcAAIAABiIgvAAIAAj1IBJAAQAkAAAVAUQAVASAAAiQAAATgIAOQgJAOgRAIQASAGAKAQQAIAOAAAWIAAATQAAAKADAKQABAMAHAFIAAAEgAD0CZIAaAAQAPAAAJgKQAHgJABgRQgBgQgHgKQgJgLgPABIgaAAgAgrEgIAAj1IAtAAIAADQIBbAAIAAAlgAmgEgIAAj1ICLAAIAAAmIhbAAIAABDIBNAAIAAAlIhNAAIAABngAnrEgQgFgGgCgMQgCgMAAgMIAAgSQAAgRgIgLQgHgKgPAAIgcAAIAABiIgvAAIAAj1IBJAAQAjAAAWAUQAVASgBAiQAAATgIAOQgIAOgRAIQASAGAJAQQAIAOABAWIAAATQAAAKACAKQACAMAHAFIAAAEgAouCZIAaAAQAOAAAIgKQAIgJAAgRQAAgQgIgKQgHgLgPABIgaAAgAsEEgIAAj1ICIAAIAAAmIhZAAIAAA9IBLAAIAAAmIhLAAIAABHIBZAAIAAAlgAt2EgIgkiXIgCAAIgjCXIgrAAIgwj1IAwAAIAYCcIACAAIAjicIAlAAIAjCcIABAAIAZicIAxAAIgxD1gA2YEgIAAj1IBRAAQAmABAUAVQAXAVAAAiQAAAkgXAVQgUAXgmAAIgiAAIAABYgA1pCiIAiAAQARAAAHgLQAJgMAAgRQAAgSgJgMQgHgMgRABIgiAAgAWHAGIAKgzIAAgnIAvAAIAAApIgYAxgATqg6QgagUABgnIAAgBIAuAAQAAAWAKAKQAKALARAAQAPAAAIgJQAIgJAAgNQAAgPgHgIQgIgJgTgHQgmgNgSgSQgUgQABgfQgBgeAXgSQAVgTAhAAQAkAAAWAUQAVATAAAjIAAAAIguAAQAAgSgJgKQgJgKgQAAQgOAAgHAKQgHAIAAAOQAAAMAJAIQAIAIAVAKQAjALASATQASARAAAfQAAAfgUASQgWASgkAAQgiAAgYgTgAK8g/QgZgXAAgqIAAifIAvAAIAACfQABAaAJANQALANATAAQARAAALgNQAKgNAAgaIAAifIAvAAIAACfQAAAqgXAXQgZAYglAAQgoAAgWgYgAvVg/QgZgXAAgqIAAifIAvAAIAACfQAAAaALANQAKANATAAQARAAALgNQALgNgBgaIAAifIAvAAIAACfQAAAqgWAXQgYAYgnAAQgoAAgWgYgAQwgqIAAj1ICJAAIAAAmIhZAAIAAA9IBLAAIAAAmIhLAAIAABHIBZAAIAAAlgAPlgqQgFgGgCgMQgBgNAAgMIAAgRQAAgSgJgKQgHgKgOAAIgdAAIAABiIgvAAIAAj1IBJAAQAkAAAWAUQAVASAAAhQgBAUgIAOQgJAOgRAIQATAGAIAPQAJAOAAAXIAAASQAAAKACALQACAMAHAEIAAAFgAOiixIAaAAQAPgBAIgIQAIgKAAgQQAAgSgIgJQgHgKgQAAIgaAAgAIlgqIAAjPIg4AAIAAgmIChAAIAAAmIg6AAIAADPgAG2gqIgOg2Ig9AAIgNA2IgyAAIBFj1IAwAAIBGD1gAF0iFIAqAAIgUhNIgBAAgACVgqIAAj1ICJAAIAAAmIhZAAIAAA9IBKAAIAAAmIhKAAIAABHIBZAAIAAAlgAgPgqIAAj1ICJAAIAAAmIhdAAIAABDIBOAAIAAAlIhOAAIAABngAkCgqIAAj1ICJAAIAAAmIhaAAIAAA9IBLAAIAAAmIhLAAIAABHIBaAAIAAAlgAmMgqIhHj1IAzAAIArDBIABAAIArjBIAzAAIhGD1gAoYgqIAAj1IAwAAIAAD1gAqagqIAAjPIg4AAIAAgmICgAAIAAAmIg6AAIAADPgAsbgqIAAj1IAvAAIAAD1gAxsgqIAAjPIg3AAIAAgmICgAAIAAAmIg6AAIAADPgAzrgqIhNicIgBAAIAACcIgvAAIAAj1IAvAAIBOCcIAAAAIAAicIAwAAIAAD1gA2/gqIAAj1IAwAAIAAD1g");
	this.shape.setTransform(0,0.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-147.2,-29.1,294.5,58.3);


(lib.Symbol35 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35475B").s().p("AsmB9QgMAHgNACQgOADgOgBQgxABgdgdQgdgdAAg0IAAhQQAAg1AdgcQAdgdAxAAQAxAAAdAdQAdAcAAA1IAABQQAAAUgEARQgFARgJAOIAkAoIglAdgAuAhmQgOAQAAAhIAABQQAAAgAOARQAMAQAZAAQAZAAAMgQQAOgRAAggIAAhQQAAghgOgQQgMgRgZAAQgZAAgMARgAMiByQgegYABgvIAAgBIA4AAQAAAbALAMQAMAMAVAAQASABAJgLQAKgKAAgRQAAgRgJgLQgJgKgYgKQgsgNgXgVQgXgUAAgkQAAglAagWQAagWAoAAQArAAAbAXQAaAYgBAqIAAABIg4AAQAAgYgLgKQgKgNgTAAQgQAAgKAMQgIAKAAARQAAANAKAKQALAKAZAMQAqAOAWAWQAWATAAAlQAAAmgZAVQgaAWgrgBQgqABgdgXgAEuBsQgdgdAAg0IAAhQQAAg1AdgcQAdgdAwAAQAxAAAdAdQAeAcAAA1IAABQQAAA0geAdQgdAdgxgBQgwABgdgdgAFWhmQgNAQAAAhIAABQQAAAgANARQANAQAYAAQAZAAANgQQANgRAAggIAAhQQAAghgNgQQgNgRgZAAQgYAAgNARgAjqByQgfgYABgvIAAgBIA4AAQAAAbAMAMQALAMAWAAQARABAKgLQAJgKAAgRQAAgRgIgLQgKgKgXgKQgtgNgXgVQgWgUAAgkQAAglAagWQAagWAoAAQAqAAAbAXQAaAYgBAqIAAABIg4AAQAAgYgKgKQgLgNgSAAQgRAAgJAMQgJAKAAARQAAANALAKQAKAKAZAMQArAOAVAWQAWATAAAlQAAAmgZAVQgaAWgqgBQgqABgdgXgAqnBsQgdgbAAgzIAAi9IA5AAIAAC9QAAAeAMARQANAPAWAAQAVAAANgPQAMgQAAgfIAAi9IA5AAIAAC9QAAAzgcAbQgdAcguAAQgvAAgcgcgAKmCFIhei6IgBAAIAAC6Ig5AAIAAkkIA5AAIBeC6IABAAIAAi6IA4AAIAAEkgACtCFIAAkkIA6AAIAAEkgAAQCFIAAj4IhBAAIAAgsIC/AAIAAAsIhFAAIAAD4gAnJCFIAAkkICkAAIAAAsIhrAAIAABKIBaAAIAAArIhaAAIAABWIBrAAIAAAtg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-96.7,-16.5,193.5,33);


(lib.Symbol34 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35475B").s().p("AC2BMQgSgRAAggIAAg1QAAggARgRQARgSAdAAQAeAAAQAPQAQAOgBAeIAAABIgiAAQAAgRgGgIQgHgHgOAAQgOAAgGAKQgHAJAAAUIAAA1QAAAUAHAJQAHAKAOAAQAOAAAGgHQAGgHAAgSIAiAAIAAABQAAAegPAOQgQAPgdAAQgdAAgRgSgAkWBMQgSgRAAggIAAh1IAjAAIAAB1QAAATAIAKQAIAKAOAAQANAAAIgKQAIgJAAgUIAAh1IAjAAIAAB1QAAAggRARQgSASgdAAQgeAAgRgSgAmnBMQgSgRAAggIAAg1QAAggARgRQARgSAcAAQAfAAAQAPQAQAOgBAeIAAABIgiAAQAAgRgGgIQgHgHgPAAQgNAAgGAKQgHAJAAAUIAAA1QAAAUAHAJQAHAKAOAAQAOAAAGgHQAGgHAAgSIAhAAIABABQAAAegPAOQgQAPgdAAQgdAAgRgSgAOlBbQgEgDgBgJIgBgTIAAgNQAAgOgGgIQgGgHgLAAIgVAAIAABJIgkAAIAAi1IA3AAQAbAAAQAOQAPAOAAAZQAAAPgGALQgGAKgNAEQAOAFAHALQAGALAAARIAAANQAAAIACAIQABAJAFAEIAAACgANzgIIATAAQALAAAGgHQAGgGAAgOQAAgMgGgIQgGgHgLAAIgTAAgALSBbIAAi1IBnAAIAAAcIhDAAIAAAuIA4AAIAAAaIg4AAIAAA1IBDAAIAAAcgAJVBbIAAi1IBmAAIAAAcIhDAAIAAAuIA4AAIAAAaIg4AAIAAA1IBDAAIAAAcgAIcBbQgEgDgBgJIgBgTIAAgNQAAgOgGgIQgGgHgLAAIgVAAIAABJIgkAAIAAi1IA3AAQAbAAAQAOQAQAOAAAZQAAAPgHALQgGAKgNAEQAOAFAHALQAGALAAARIAAANQAAAIACAIQABAJAFAEIAAACgAHqgIIATAAQALAAAHgHQAFgGAAgOQAAgMgFgIQgGgHgMAAIgTAAgAGSBbIgLgoIgtAAIgLAoIglAAIA0i1IAlAAIA1C1gAFhAYIAgAAIgQg5IgBAAgAAPBbIAAiZIgoAAIAAgcIB3AAIAAAcIgsAAIAACZgAiMBbIAAi1IAjAAIAACZIBFAAIAAAcgAn2BbIAAi1IAjAAIAAC1gAp2BbIAAi1IBpAAIAAAcIhFAAIAAAzIA6AAIAAAaIg6AAIAABMgArzBbIAAi1IBpAAIAAAcIhFAAIAAAzIA6AAIAAAaIg6AAIAABMgAs0BbIAAi1IAjAAIAAC1gAvJBbIAAi1IA4AAQAdAAASAVQATAWAAAhIAAAdQAAAhgTAWQgSAVgdAAgAumA/IAVAAQAOAAAIgNQAJgOAAgVIAAgdQAAgVgJgOQgIgNgOAAIgVAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-97,-9.4,194.1,18.9);


(lib.Symbol33 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35475B").s().p("AsFBkQgXgYAAgrIAAhBQAAgrAXgYQAZgYAnAAQAoAAAYAYQAZAYAAArIAABBQAAArgZAYQgYAYgoAAQgnAAgZgYgArjhIQgLANAAAbIAABBQAAAbALANQAKAOAUAAQAVAAAJgOQAMgNAAgbIAAhBQAAgbgMgNQgJgOgVAAQgUAAgKAOgAOgB4IAAhlIhNAAIAABlIgvAAIAAjvIAvAAIAABoIBNAAIAAhoIAuAAIAADvgAKlB4IAAjLIg3AAIAAgkICfAAIAAAkIg4AAIAADLgAImB4IAAjvIAuAAIAADvgAGyB4IgjiUIgBAAIgjCUIgrAAIgwjvIAwAAIAYCXIABAAIAjiXIAkAAIAjCXIACAAIAYiXIAwAAIgwDvgAAYB4IAAjvIBQAAQAkAAAVAVQAWAVAAAjQAAAigWAUQgVAVgkAAIgiAAIAABXgABGgCIAiAAQAQAAAIgLQAIgMAAgRQAAgSgIgLQgIgMgQAAIgiAAgAiMB4IAAjvIAvAAIAADKIBbAAIAAAlgAkxB4IAAjvICIAAIAAAkIhZAAIAAA+IBKAAIAAAiIhKAAIAABGIBZAAIAAAlgAmEB4IAAhlIhPAAIAABlIguAAIAAjvIAuAAIAABoIBPAAIAAhoIAuAAIAADvgAuWB4IAAjLIg3AAIAAgkICeAAIAAAkIg5AAIAADLg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-97.5,-12.4,195,24.9);


(lib.Symbol32 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35475B").s().p("AtBBsQgKAGgLABQgMADgNAAQgpAAgZgZQgagZAAgtIAAhFQAAgtAagZQAZgZApAAQArAAAYAZQAaAZAAAtIAABFQAAARgEAQQgEAOgIALIAgAjIghAagAuPhYQgLAOAAAcIAABFQAAAcALAOQALAOAVAAQAWAAALgOQALgOAAgcIAAhFQAAgcgLgOQgLgPgWAAQgVAAgLAPgAJWBdQgYgZAAgtIAAhFQAAgtAYgZQAagZAqAAQAqAAAZAZQAaAZAAAtIAABFQAAAtgaAZQgZAZgqAAQgqAAgagZgAJ5hYQgLAOAAAcIAABFQAAAcALAOQALAOAWAAQAVAAALgOQALgOAAgcIAAhFQAAgcgLgOQgLgPgVAAQgWAAgLAPgACCBeQgXgYAAgtIAAhJQAAgsAXgZQAXgYAnAAQAqAAAXAUQAWAVgBAoIAAABIgwAAQAAgYgIgJQgJgLgVAAQgSAAgJAOQgJANAAAbIAABKQAAAcAJANQAKANAUAAQATAAAIgJQAIgKAAgYIAvAAIABABQAAApgVATQgWAVgoAAQgoAAgZgYgAjrBiQgagUABgpIAAgBIAxAAQAAAXAKALQAKAKASAAQAPAAAIgJQAIgJAAgOQAAgPgHgJQgIgJgUgIQgngLgTgSQgUgRAAggQAAggAWgSQAXgUAiAAQAlAAAXAVQAXAUgBAkIAAABIgwAAQAAgUgJgJQgJgMgRAAQgOAAgIAKQgHAJAAAPQAAAMAJAIQAJAJAVAKQAlAMATATQASAQAAAgQAAAggVATQgWATglAAQgkAAgagUgArfBiQgUgTAAggQAAgVAJgPQAJgNAUgRIACgBQgLgPgEgOQgFgMAAgPQAAgfAQgRQARgRAeAAQAZAAAQARQAQARAAAYQAAASgGAOQgHANgNAKIgRANIApAzIABAAQAGgJACgMQADgLAAgLIAnAAQAAAWgGAVQgGAVgLAOIAhArIg4AAIgMgPQgNAKgNAFQgPAEgQAAQgiAAgUgUgAq/AcQgDAIAAAIQAAAPAIALQAIAJANAAQAIAAAHgBQAIgDAIgEIgug9QgIAJgDAJgAqvhfQgFAIAAALQAAAHADAIQADAHAGAJIAJgHQAJgHADgHQADgGAAgIQAAgJgEgHQgFgHgJAAQgIAAgFAIgAObByIhQifIgCAAIAACfIgxAAIAAj7IAxAAIBRCfIABAAIAAifIAxAAIAAD7gAHoByIAAj7IAxAAIAAD7gAFgByIAAjVIg6AAIAAgmICnAAIAAAmIg8AAIAADVgAg8ByIAAj7ICMAAIAAAmIhbAAIAABBIBLAAIAAAkIhLAAIAABKIBbAAIAAAmgAmUByIgPg3Ig/AAIgOA3IgzAAIBHj7IAzAAIBID7gAnYAVIAsAAIgWhPIgBAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-97.2,-14.3,194.5,28.6);


(lib.Symbol28 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CBCBCB").s().p("Aj6ARIAAghIH1AAIAAAhg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-25.1,-1.7,50.3,3.5);


(lib.Symbol26 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqTGoQgiABgXgZQgYgYAAgiIAAjeIjqAIIDqjwIAAjlQAAgjAYgYQATgVAcgCIYlAAQAbACAUAVQAYAYAAAjIAAKrQAAAigYAYQgXAZgigBg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-97.5,-42.5,195.1,85);


(lib.Symbol23 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CBCBCB").s().p("AgIAJQgEgEgBgFQABgEAEgEQAEgEAEgBQAFABAEAEQAEAEABAEQgBAFgEAEQgEAEgFABQgEgBgEgEg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1.4,-1.4,2.8,2.8);


(lib.Symbol22 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CBCBCB").s().p("AmzEWINngEIgBAcItmAGgAmzCvIF4gCIgBAdIl3ACgAmzB8INSgEIAAAcItSAGgAmzBJINSgFIgBAdItRAFgAmzAWINRgFIABAeItSAEgAmzgbINQgEIABAdItRADgAmzhNINQgGIABAeItRAEgAmziBINRgFIAAAdItRAGgAmzizINQgEIAAAcItQAFgAmzjmINPgFIABAdItQAFgAlakwII1gDIAAAeIo2ADg");
	this.shape.setTransform(6.1,-34.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ApLs1ISOgGIAJZwIyOAHgAl3g+IAAAdINngFIABgdgAl3imIAAAeIF3gCIAAgegAl3jYIAAAdINTgFIAAgdgAl3kMIAAAdINSgEIABgdgAl3k+IAAAdINTgFIgBgdgAl3lxIAAAdINSgEIgBgegAl3mkIAAAcINSgDIgBgegAl3nYIAAAfINSgHIAAgcgAl3oJIAAAcINRgEIAAgdgAl3o9IAAAdINRgEIgBgdgAkdqHIgBAeII2gDIAAgdg");

	// Layer 2
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(51,51,51,0.6)").s().p("ApLs2ISPgFIAIZxIyOAGgAl2g/IAAAfINmgHIABgcgAl2imIAAAdIF2gBIAAgdgAl2jZIAAAeINRgFIAAgcgAl2kLIAAAcINQgEIABgdgAl2k+IAAAdINRgFIgBgdgAl2lxIAAAeINQgGIgBgdgAl2mkIAAAdINQgFIgBgegAl2nYIAAAeINQgFIAAgegAl2oKIAAAeINPgFIAAgdgAl2o8IAAAcINPgEIgBgegAkdqGIgBAdII2gCIAAgfg");
	this.shape_2.setTransform(3.2,3.2);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-58.8,-82.8,120.9,168.9);


(lib.Symbol19 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#35475B").s().p("AGPGlQgVgVAAgnIAAiRIArAAIAACRQAAAXAJAMQAJAMARAAQAQAAAKgMQAJgLAAgYIAAiRIArAAIAACRQAAAngVAVQgWAVgjAAQgjAAgWgVgADjGoQgXgRABglIAAAAIAqAAQAAAUAJAKQAIAJAQAAQAOAAAHgHQAHgJAAgMQAAgNgGgIQgHgIgSgHQghgLgSgRQgRgOAAgcQAAgcATgQQAUgRAfAAQAfgBAUATQAUARAAAgIAAAAIgrAAQAAgQgHgJQgIgKgPAAQgMABgHAHQgGAJAAAMQAAAMAIAHQAHAHAUAJQAfALARAQQAQAQAAAcQAAAcgSAQQgUARghAAQgfAAgWgSgAoJGlQgWgVAAgnIAAiRIArAAIAACRQAAAXAKAMQAJAMAQAAQAQAAAKgMQAJgLAAgYIAAiRIArAAIAACRQAAAngVAVQgWAVgjAAQgjAAgVgVgArHGlQgWgXAAgmIAAg/QAAgnAWgXQAWgVAlAAQAkAAAWAVQAXAXAAAnIAAA/QAAAmgXAXQgWAVgkAAQglAAgWgVgAqpEEQgKAMAAAZIAAA/QAAAXAKANQAKAMATAAQASAAAKgMQAKgNAAgXIAAg/QAAgZgKgMQgKgMgSAAQgTAAgKAMgAMcG3IAAjfIB8AAIAAAjIhRAAIAAA4IBEAAIAAAhIhEAAIAABBIBRAAIAAAigALPG3IAAiMIAAAAIgoCMIgeAAIgniLIgBAAIAACLIgrAAIAAjfIA4AAIApClIABAAIAqilIA4AAIAADfgAA7G3IAAjfIB8AAIAAAjIhRAAIAAA4IBEAAIAAAhIhEAAIAABBIBRAAIAAAigAgIG3QgFgFgBgLQgCgMAAgKIAAgQQAAgQgHgJQgHgKgNAAIgaAAIAABZIgrAAIAAjfIBCAAQAhAAARASQAUARAAAeQAAASgIAOQgIAMgOAHQAPAGAIANQAIAOAAAUIAAARQAAAJACAKQACAKAGAEIAAAEgAhFE8IAXAAQAOABAHgKQAIgHAAgQQAAgPgIgJQgHgJgOAAIgXAAgAj6G3QgEgFgDgLIAAgWIAAgQQAAgQgIgJQgHgKgNAAIgaAAIAABZIgrAAIAAjfIBDAAQAhAAATASQATARAAAeQAAASgIAOQgIAMgPAHQARAGAIANQAIAOAAAUIAAARQAAAJACAKQABAKAHAEIAAAEgAk3E8IAYAAQANABAHgKQAIgHAAgQQAAgPgIgJQgGgJgOAAIgYAAgAtYG3IAAhSIg/iNIAvAAIAmBhIABAAIAmhhIAvAAIhBCQIAABPgAMlCbQgSgSAAggIAAgzQAAghASgSQASgQAeAAQAeAAASAQQATASAAAhIAAAzQAAAggTASQgSASgeAAQgeAAgSgSgAM+AXQgIALAAAUIAAAzQAAAUAIAKQAIALAPAAQAPAAAIgLQAIgKAAgUIAAgzQAAgUgIgLQgIgKgPAAQgPAAgIAKgABSCbQgSgRAAgfIAAg2QAAggARgSQARgPAcgBQAfAAAPANQAQAPAAAdIAAABIgjAAQAAgRgGgIQgGgHgPAAQgNAAgHAKQgGAJAAAUIAAA3QAAATAHAKQAHAKAOAAQAOAAAFgIQAGgGAAgSIAiAAIABABQAAAdgQAPQgPAOgdAAQgcAAgSgSgAK2CrIAAibIgqAAIAAgaIB5AAIAAAaIgrAAIAACbgAH1CrIAAhEIg0hxIAnAAIAfBNIABAAIAghNIAmAAIg1B0IAABBgAFRCrIAAi1IAkAAIAACZIBEAAIAAAcgADxCrIAAibIgpAAIAAgaIB4AAIAAAaIgrAAIAACbgAg3CrIAAi1IBkAAIAAAaIhBAAIAAAuIA2AAIAAAcIg2AAIAAA1IBBAAIAAAcgAhwCrQgEgEgBgJIgCgTIAAgNQAAgNgFgIQgGgIgLAAIgVAAIAABKIgjAAIAAi1IA2AAQAbAAAQAMQAQAOAAAZQAAAOgGALQgHALgNAFQAOAGAHAKQAGALAAARIAAAOQAAAIACAHQACAJAEAFIAAACgAiiBGIATAAQALAAAHgIQAGgGAAgMQAAgNgGgIQgGgHgMAAIgTAAgAkGCrIAAi1IAjAAIAAC1gAmcCrIAAi1IA5AAQAcAAATATQATAWAAAgIAAAfQAAAjgTAVQgTAUgcABgAl4CPIAVAAQANAAAJgOQAIgNAAgWIAAgfQAAgUgIgOQgJgNgNAAIgVAAgApoCrIAAi1IA5AAQAcAAATATQASAWAAAgIAAAfQAAAjgSAVQgTAUgcABgApFCPIAWAAQANAAAJgOQAIgNAAgWIAAgfQAAgUgIgOQgJgNgNAAIgWAAgAr7CrIAAi1IA4AAQAdAAATATQASAWAAAgIAAAfQAAAjgSAVQgTAUgdABgArXCPIAUAAQAOAAAIgOQAJgNAAgWIAAgfQAAgUgJgOQgIgNgOAAIgUAAgAswCrIgKgoIguAAIgKAoIgkAAIAzi1IAlAAIA0C1gAthBnIAgAAIgPg6IgBAAgAIkg4QgQgRAAgdIAAgyQAAgeAPgQQAQgQAaAAQAcAAAPANQAPAOgBAbIAAAAIggAAQAAgPgFgHQgGgGgOAAQgNAAgFAIQgGAJAAASIAAAzQAAASAGAKQAHAIANAAQAMAAAGgGQAFgHAAgQIAgAAIAAAAQAAAcgOAOQgOANgbAAQgbAAgQgQgAFjg4QgRgQAAgdIAAhvIAhAAIAABvQAAARAHAKQAHAIANAAQAMAAAHgIQAIgKAAgRIAAhvIAgAAIAABvQAAAdgQAQQgQAQgbAAQgbAAgQgQgADRg4QgQgSAAgdIAAgxQAAgdAQgQQARgRAcAAQAcAAARARQARAQAAAdIAAAxQAAAdgRASQgRAQgcAAQgcAAgRgQgADpizQgIAKAAARIAAAxQAAASAIAJQAHAKAOAAQAOAAAIgKQAIgJAAgSIAAgxQAAgRgIgKQgIgJgOAAQgOAAgHAJgAhpg1QgRgOABgcIAAAAIAgAAQAAAQAGAHQAHAHANAAQAKAAAFgGQAFgGAAgKQAAgKgEgGQgGgGgNgFQgagJgNgMQgOgMAAgVQAAgVAQgMQAOgNAYAAQAYAAAQANQAPAOgBAYIAAABIggAAQAAgNgGgHQgGgHgLAAQgKAAgFAGQgFAGAAAJQAAAJAHAGQAGAFAOAHQAYAIANANQAMAMAAAVQAAAWgOAMQgPANgYAAQgZAAgRgNgAldg1QgSgOABgcIAAAAIAgAAQAAAQAHAHQAGAHANAAQAKAAAFgGQAGgGAAgKQAAgKgFgGQgFgGgOgFQgagJgNgMQgNgMAAgVQAAgVAPgMQAPgNAXAAQAYAAAQANQAPAOgBAYIAAABIggAAQAAgNgGgHQgGgHgLAAQgJAAgGAGQgEAGAAAJQAAAJAGAGQAFAFAPAHQAYAIANANQANAMAAAVQAAAWgPAMQgPANgYAAQgZAAgQgNgAN3grIg2hsIAABsIghAAIAAipIAhAAIA2BsIAAAAIAAhsIAhAAIAACpgALwgrIgKgkIgqAAIgKAkIgiAAIAwipIAiAAIAxCpgALChqIAeAAIgPg1IAAAAgABjgrIAAg/IgxhqIAkAAIAeBJIAAAAIAehJIAjAAIgxBtIAAA8gAjpgrIAAipIBfAAIAAAZIg+AAIAAAsIA0AAIAAAZIg0AAIAAAyIA+AAIAAAZgAmbgrIgJgkIgqAAIgKAkIgiAAIAwipIAiAAIAwCpgAnIhqIAdAAIgOg1gAokgrQgDgDgCgIIgBgSIAAgLQAAgNgFgHQgGgIgKABIgTAAIAABDIghAAIAAipIAzAAQAZAAAOANQAPANAAAYQAAANgGAKQgGAKgMAEQANAFAGALQAGAKAAAQIAAAMIACAPQABAIAFADIAAACgApSiIIASAAQAKAAAGgHQAFgFAAgNQAAgLgFgHQgGgHgKgBIgSAAgAqugrIAAhHIg3AAIAABHIghAAIAAipIAhAAIAABJIA3AAIAAhJIAgAAIAACpgAuMgrIAAipIA5AAQAaAAAPAPQAPAPAAAYQAAAYgPAQQgPAOgaAAIgYAAIAAA9gAtriCIAYAAQAMAAAFgHQAGgIAAgNQAAgMgGgJQgFgIgMAAIgYAAgAMtkMQgSgSAAggIAAg3QAAggARgSQARgSAcAAQAfAAARAOQAQAQgBAeIAAABIgjAAQAAgSgGgHQgGgIgQAAQgNAAgHAKQgHAKAAATIAAA4QAAAVAIAJQAHAKAOAAQAOAAAGgIQAGgHAAgRIAiAAIABAAQAAAfgPAOQgQAPgeAAQgdAAgRgSgAGWkMQgRgSAAggIAAg3QAAggAQgSQARgSAdAAQAfAAAQAOQAQAQAAAeIAAABIgjAAQAAgSgGgHQgHgIgPAAQgNAAgHAKQgGAKAAATIAAA4QAAAVAHAJQAHAKAOAAQAOAAAGgIQAGgHAAgRIAiAAIABAAQAAAfgQAOQgQAPgdAAQgdAAgSgSgAgGkJQgSgOABgfIAAAAIAhAAQAAARAHAHQAHAJAOgBQALAAAGgGQAFgGAAgLQAAgLgFgHQgGgGgPgGQgcgKgMgMQgOgNAAgXQAAgYAQgOQAPgOAZAAQAbAAAQAQQARAPgBAZIAAABIgjAAQAAgOgGgHQgHgJgMABQgKAAgGAHQgFAHAAALQAAAIAGAGQAHAGAPAIQAbAIAOAOQANANAAAYQAAAYgPANQgRAOgaAAQgbAAgRgPgAt9kMQgSgSAAggIAAg3QAAggARgSQASgSAcAAQAfAAAQAOQARAQgCAeIAAABIgjAAQAAgSgFgHQgHgIgPAAQgOAAgGAKQgHAKAAATIAAA4QAAAVAIAJQAHAKAOAAQAOAAAGgIQAFgHAAgRIAjAAIAAAAQAAAfgPAOQgPAPgeAAQgdAAgSgSgALcj9IAAi5IAkAAIAAC5gAJbj9IAAi5IBqAAIAAAcIhGAAIAAAzIA7AAIAAAdIg7AAIAABNgAIaj9IAAi5IAkAAIAAC5gAEJj9IAAi5IBoAAIAAAcIhEAAIAAAvIA5AAIAAAcIg5AAIAAA3IBEAAIAAAbgAB4j9IAAi5IA+AAQAcABAQAPQAQAQAAAbQAAAbgQAQQgQAQgcAAIgbAAIAABDgACbldIAbAAQANABAFgJQAGgIAAgNQAAgOgGgKQgFgIgNAAIgbAAgAiGj9QgEgEgBgJIgCgTIAAgMQAAgOgFgIQgGgJgLAAIgWAAIAABLIgkAAIAAi5IA4AAQAbABARAOQAPAOAAAZQAAAOgGALQgHALgNAGQAOAFAHAMQAGAKAAASIAAANQAAAIADAIQABAJAFADIAAADgAi5lkIAUAAQALAAAGgGQAGgHAAgNQAAgNgGgHQgGgIgLAAIgUAAgAlbj9IAAi5IBoAAIAAAcIhEAAIAAAvIA5AAIAAAcIg5AAIAAA3IBEAAIAAAbgAnaj9IAAi5IBoAAIAAAcIhEAAIAAAvIA5AAIAAAcIg5AAIAAA3IBEAAIAAAbgAoTj9QgEgEgCgJIgBgTIAAgMQAAgOgGgIQgFgJgLAAIgWAAIAABLIgkAAIAAi5IA4AAQAbABAQAOQAQAOAAAZQAAAOgHALQgGALgNAGQAPAFAGAMQAGAKAAASIAAANQAAAIACAIQACAJAFADIAAADgApGlkIAUAAQALAAAGgGQAGgHAAgNQAAgNgGgHQgGgIgLAAIgUAAgAqej9IgLgoIguAAIgLAoIglAAIA0i5IAlAAIA1C5gArQlCIAgAAIgQg6IAAAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-92,-44.2,184.1,88.5);


(lib.Symbol16 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#81CBB5").s().p("EhCXBCXUgbegbgAAAgm3UAAAgm2AbegbhUAbhgbeAm2AAAUAm3AAAAbgAbeUAbfAbhAAAAm2UAAAAm3gbfAbgUgbgAbfgm3AAAUgm2AAAgbhgbfg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-600.7,-600.7,1201.4,1201.4);


(lib.Symbol15 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(51,51,51,0.6)").s().p("Ak6m6IJygBIADN1IpyACgAkGieIABAAIAAgTIgBAAgAgPixIAMAAIAAAAgAkGi8IAAAAIAAgTIAAAAgAgbjPIAYAAIAAgBgAkGjbIAAAAIAAgTIAAAAgAgPjuIAMAAIAAAAgAkHmSIAbAAIgbAAg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.5,-44.4,63.2,89);


(lib.Symbol14 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF841D").s().p("AJzA4QgNgNAAgZIAAgkQAAgXANgOQAOgOAXAAQAWAAANAOQAPAOAAAXIAAAkQAAAZgPANQgNAOgWAAQgXAAgOgOgAKGgoQgGAHAAAPIAAAkQAAAQAGAHQAGAIAMAAQALAAAGgIQAGgHAAgQIAAgkQAAgPgGgHQgGgIgLAAQgMAAgGAIgAIAA4QgOgNAAgZIAAgkQAAgXAOgOQANgOAXAAQAXAAAOAOQANAOAAAXIAAAkQAAAZgNANQgOAOgXAAQgXAAgNgOgAITgoQgGAHAAAPIAAAkQAAAQAGAHQAGAIALAAQAMAAAFgIQAHgHAAgQIAAgkQAAgPgHgHQgFgIgMAAQgLAAgGAIgAg3A4QgNgNAAgZIAAgkQAAgXANgOQAOgOAWAAQAVAAAOAOQAOAOAAAXIAAAkQAAAZgOANQgOAOgVAAQgWAAgOgOgAgkgoQgGAHAAAPIAAAkQAAAQAGAHQAGAIALAAQAMAAAGgIQAEgHAAgQIAAgkQAAgPgEgHQgGgIgMAAQgLAAgGAIgAjRA7QgOgLABgXIAAAAIAZAAQAAANAGAFQAFAGAKABQAIgBAFgFQAEgEAAgIQAAgIgEgFQgFgFgKgEQgVgHgLgIQgKgJAAgSQAAgQAMgLQAMgJATgBQATAAANALQAMALgBAUIAAABIgaAAQAAgMgFgFQgEgGgJABQgHgBgFAGQgEAEAAAIQAAAGAFAFQAFAFALAGQAUAGAKAIQAKAKAAARQAAASgLAJQgMALgUAAQgTgBgOgKgApbA4QgNgNAAgZIAAgkQAAgXANgOQANgOAXAAQAXAAANAOQAOAOAAAXIAAAkQAAAZgOANQgNAOgXAAQgXAAgNgOgApIgoQgGAHAAAPIAAAkQAAAQAGAHQAGAIALAAQALAAAGgIQAHgHAAgQIAAgkQAAgPgHgHQgGgIgLAAQgLAAgGAIgAMbBEIgeg6IgHAAIAAA6IgbAAIAAiGIAbAAIAAA3IAFAAIAeg3IAgAAIgnA9IAqBJgAGYBEIAAiGIAaAAIAABxIAzAAIAAAVgAEQBEIAAiGIAbAAIAABxIAzAAIAAAVgADqBEIgIgeIgiAAIgIAeIgbAAIAmiGIAcAAIAnCGgADFARIAYAAIgMgqIAAAAgAB2BEIgrhWIgBAAIAABWIgaAAIAAiGIAaAAIArBUIABAAIAAhUIAaAAIAACGgAhyBEIAAiGIAaAAIAACGgAk4BEIAAiGIBMAAIAAAUIgyAAIAAAjIAqAAIAAASIgqAAIAAAoIAyAAIAAAVgAmWBEIAAiGIBOAAIAAAUIgzAAIAAAmIArAAIAAASIgrAAIAAA6gAnzBEIAAiGIBOAAIAAAUIg0AAIAAAmIAsAAIAAASIgsAAIAAA6gAqQBEQgDgDgBgGIgBgPIAAgKQAAgJgEgHQgFgFgIAAIgQAAIAAA3IgaAAIAAiGIApAAQAUAAAMAKQALAKAAAUQAAAKgFAIQgEAIgKACQALADAFAJQAEAIAAAMIAAAKQAAAHACAGQABAFADADIAAADgAq2gGIAPAAQAIAAAFgFQAEgFAAgKQAAgJgEgFQgFgGgIAAIgPAAgAs7BEIAAiGIAtAAQAVAAAMAMQAMALAAATQAAAUgMAKQgMAMgVAAIgTAAIAAAygAshAAIATAAQAJAAAFgHQAFgGAAgKQAAgLgFgGQgFgGgJAAIgTAAg");
	this.shape.setTransform(-3.8,46.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-86.6,39.9,165.8,14);


(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF841D").s().p("AMqCTIALg1IAAgnIAtAAIAAApIgYAzgADTBRQgYgUABgnIAAgBIAuAAQAAAWAJALQAJAKASAAQAPAAAHgJQAIgIAAgOQAAgOgHgJQgHgJgVgFQgkgNgTgRQgSgQAAgeQAAgeAVgSQAVgSAiAAQAiAAAXATQAUATgBAiIAAACIgtAAQAAgTgJgKQgJgKgOAAQgOAAgIAJQgGAJAAANQAAAMAIAIQAJAJAUAJQAjALARASQASAQAAAeQAAAfgUASQgVASgjAAQgjAAgYgTgAAcBRQgZgUABgnIAAgBIAuAAQAAAWAJALQAKAKASAAQAOAAAIgJQAHgIAAgOQAAgOgHgJQgIgJgTgFQgkgNgTgRQgTgQAAgeQAAgeAVgSQAWgSAgAAQAkAAAWATQAVATgBAiIAAACIgtAAQAAgTgJgKQgJgKgPAAQgNAAgIAJQgHAJAAANQAAAMAJAIQAIAJAUAJQAjALASASQARAQAAAeQAAAfgTASQgVASgjAAQgjAAgYgTgAKPBgIAAjvICHAAIAAAkIhYAAIAAA9IBJAAIAAAlIhJAAIAABFIBYAAIAAAkgAIFBgIhEjvIAxAAIArC8IABAAIAri8IAyAAIhFDvgAF7BgIAAjvIAvAAIAADvgAiZBgIAAjvICHAAIAAAkIhYAAIAAA9IBKAAIAAAlIhKAAIAABFIBYAAIAAAkgAjkBgQgFgFgCgMIgBgYIAAgSQAAgRgIgLQgHgJgQAAIgbAAIAABgIgvAAIAAjvIBJAAQAjAAAVASQAVATAAAiQAAASgJAOQgIAOgRAIQASAHAJAMQAJAOAAAWIAAASQAAALACALQACALAHAEIAAAEgAkmgjIAaAAQAOAAAIgJQAIgJAAgRQAAgRgIgKQgHgKgPAAIgaAAgAoSBgIAAjvIBQAAQAlAAAVAVQAWAVAAAiQAAAjgWAVQgVAUglAAIgiAAIAABXgAnkgaIAiAAQARAAAHgLQAJgMAAgRQAAgSgJgMQgHgLgRAAIgiAAgApmBgIAAiWIAAAAIgsCWIgfAAIgsiVIAAAAIAACVIgvAAIAAjvIA8AAIAtCxIABAAIAuixIA9AAIAADvgAthBgIAAjvIAvAAIAADvg");
	this.shape.setTransform(0.2,56.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-86.5,41.4,173.4,29.6);


(lib.Symbol12 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF841D").s().p("ADzBIQgRgRgBgfIAAgwQABgfARgQQARgRAdgBQAdABARARQASAQAAAfIAAAwQAAAfgSARQgRASgdgBQgdABgRgSgAELg0QgIAKAAASIAAAwQAAASAIAMQAIAJAOAAQAOAAAJgJQAHgMAAgSIAAgwQAAgSgHgKQgJgLgOABQgOgBgIALgAg/BMQgTgPACgcIAAAAIAgAAQAAAPAHAIQAGAHANAAQALABAGgHQAFgGAAgKQAAgKgFgGQgFgGgPgHQgagIgNgLQgOgLAAgXQAAgVAPgNQAQgOAYAAQAYABAQAOQAPAOgBAYIAAABIgfAAQAAgOgHgGQgFgIgMAAQgJAAgGAHQgFAGAAAKQAAAJAGAFQAGAGAQAHQAXAJAMALQAOAMAAAWQAAAXgPANQgQANgYgBQgZABgQgOgAlkBJQgRgRAAgeIAAgzQAAgfAQgQQARgQAcgBQAcAAAPAOQAPANgBAaIggAAQgBgOgFgGQgHgGgMAAQgMAAgIAJQgHAJgBASIAAA0QABASAHAKQAIAJANAAQAKAAAGgCQAGgCADgFIAAgjIgbAAIAAgVIA9AAIAABCQgIAKgOAIQgOAIgXgBQgcAAgRgQgAorBMQgRgPAAgcIAAAAIAiAAQAAAPAHAIQAGAHANAAQALABAFgHQAGgGgBgKQAAgKgDgGQgHgGgNgHQgbgIgOgLQgNgLAAgXQAAgVAPgNQAPgOAZAAQAZABAQAOQAPAOAAAYIAAABIgiAAQAAgOgGgGQgGgIgLAAQgKAAgFAHQgFAGgBAKQABAJAFAFQAGAGAPAHQAaAJANALQANAMAAAWQAAAXgPANQgPANgagBQgZABgSgOgAMbBXIg4huIAAAAIAABuIgiAAIAAiuIAiAAIA3BvIABAAIAAhvIAiAAIAACugAKPBXIgKgnIgrAAIgKAnIgkAAIAxiuIAkAAIAyCugAJgAWIAeAAIgPg1IAAAAgAHLBXQgEgDgBgKIgCgRIAAgNQABgNgGgHQgFgIgLABIgUAAIAABGIgiAAIAAiuIA0AAQAaABAPAOQAPANABAYQgBANgGALQgGAKgNADQAOAFAGALQAHAKAAAQIAAANQAAAIABAIQACAIAFADIAAADgAGbgIIASAAQALAAAFgHQAHgGgBgMQABgNgHgGQgEgIgMAAIgSAAgABsBXIAAiuIBlAAIAAAbIhCAAIAAAxIA3AAIAAAZIg3AAIAABJgAiKBXIg3huIgBAAIAABuIgiAAIAAiuIAiAAIA3BvIABAAIAAhvIAiAAIAACugAmwBXIAAiuIAiAAIAACugAqvBXIAAiuIBiAAIAAAbIhAAAIAAAtIA1AAIAAAYIg1AAIAAA0IBAAAIAAAagAs8BXIAAiuIA3AAQAaAAATAVQARAUAAAgIAAAcQAAAggRAVQgTAUgaAAgAsbA9IAWAAQANgBAHgNQAIgNAAgUIAAgcQAAgUgIgMQgHgNgNgBIgWAAg");
	this.shape.setTransform(-3.7,62.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-86.6,53.1,165.9,18);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF841D").s().p("AHmA9QgPgOAAgZIAAheIAdAAIAABeQAAAPAGAIQAGAIALAAQALAAAGgIQAGgIAAgPIAAheIAcAAIAABeQAAAZgNAOQgPAOgXAAQgXAAgOgOgAFzBAQgPgMABgYIAAAAIAcAAQAAANAFAGQAGAHALAAQAJAAAEgGQAFgFAAgIQAAgJgEgFQgFgFgMgFQgWgIgLgIQgMgKAAgSQAAgTANgLQANgLAUAAQAWAAANAMQANAMAAAVIgcAAQAAgLgGgGQgFgGgJAAQgIAAgFAGQgEAFAAAIQAAAHAFAFQAFAFAMAGQAWAHALAJQAKAKAAATQAAATgMAKQgNALgVAAQgVAAgPgLgAh0A9QgOgOAAgZIAAgqQAAgaANgOQANgOAXAAQAZAAANALQANAMgBAYIAAABIgcAAQAAgOgFgGQgFgGgMAAQgKAAgGAIQgFAIAAAPIAAArQAAAPAGAIQAGAIALAAQALAAAEgGQAFgFAAgOIAbAAIABAAQAAAYgMALQgNAMgXAAQgXAAgOgOgAmBA9QgOgOAAgZIAAgqQAAgaAOgOQANgOAXAAQAYAAANALQANAMgBAYIAAABIgbAAQAAgOgFgGQgFgGgMAAQgLAAgFAIQgFAIAAAPIAAArQAAAPAFAIQAGAIAMAAQAKAAAFgGQAFgFAAgOIAbAAIAAAAQAAAYgMALQgMAMgXAAQgYAAgOgOgAsvA9QgOgPAAgaIAAgnQAAgaAOgOQAOgPAZAAQAYAAAPAPQAPAOAAAaIAAAnQAAAagPAPQgPAOgYAAQgZAAgOgOgAsbgrQgGAIAAAQIAAAnQAAAQAGAJQAGAIANAAQAMAAAHgIQAGgJAAgQIAAgnQAAgQgGgIQgHgJgMAAQgNAAgGAJgALsBJIAAiRIBSAAIAAAWIg1AAIAAAmIAtAAIAAAUIgtAAIAAArIA1AAIAAAWgAK5BJIAAhbIAAAAIgaBbIgUAAIgahaIgBAAIAABaIgcAAIAAiRIAlAAIAbBrIABAAIAbhrIAmAAIAACRgAEEBJIAAiRIBSAAIAAAWIg1AAIAAAmIAsAAIAAAUIgsAAIAAArIA1AAIAAAWgADWBJQgCgDgCgHIgBgPIAAgLQAAgKgEgHQgFgGgJAAIgRAAIAAA7IgcAAIAAiRIAsAAQAWAAAMALQANAMAAAUQAAALgFAJQgGAIgKADQALAFAFAIQAGAJAAANIAAALIABANQABAHAEADIAAACgACugGIAQAAQAIAAAGgGQAEgFAAgKQAAgLgEgFQgFgHgJAAIgQAAgAA1BJIggg9IgIAAIAAA9IgaAAIAAiRIAaAAIAAA8IAGAAIAfg8IAjAAIgqBEIAuBNgAi0BJIAAiRIAdAAIAACRgAkaBJIAAiRIAdAAIAAB7IA3AAIAAAWgApABJIAAiRIBTAAIAAAWIg3AAIAAAmIAuAAIAAAUIguAAIAAArIA3AAIAAAWgApzBJIgvhcIAAAAIAABcIgdAAIAAiRIAdAAIAvBcIAAhcIAcAAIAACRgAnZAWIAAgWIAzAAIAAAWg");
	this.shape.setTransform(-3.8,66.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-86.9,59.3,166.2,15.2);


(lib.Symbol3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EF841D").s().p("Eg43AHCIAAuDMBxuAAAIAAODg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-364,-45,728,90);


(lib.Path_21 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ao2lmIBHgsIiIjcIA4giQhFgXg5grQg+gugrhDQhDhpgjhuQgghnglg1QgjAZgrAAQgsAAgjgbQgqgigGg1QgGg3AigoIAAAAIgCgCIgiAXQgtAeg0gIQg1gIgfgrQgZgkABgrQABgsAaggIgoASQgxAXgygRQgzgQgYgvQgYgwARg0QARgzAwgXIAEgCIgEgWIknAAIAAgrIhjgcQgSgFAAgKQABgJARgEIBkgbIABgdIB/AAQgHgtAWgpQAYgpArgPIKBjYQAdgJAdADQAcgDAZAIIIVCeQAfAHAYAVQAYAVAMAfIATB7IA0ABIAAgBIA0ABIAAggIJZABIgBgeIogAdIgBgaIJAgdIABA4IAqAAIAGDZIqjAAIgBggIhUAAIBUIbICCDdIA3giICIDcIBHgsMAZyAptItWIQg");
	this.shape.setTransform(193.7,231.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,387.5,462.3);


(lib.Path = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BF9880").s().p("AgQABIABgGIAAgDIAPACIAAAAQAHgBAIgCIACAKQgGAJgLAAQgJAAgHgJg");
	this.shape.setTransform(1.8,1.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,3.5,2.1);


(lib.Symbol44 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#24C8DD").s().p("AjhDdIAAm5IEbAAICoDbIioDeg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.6,-22.1,45.3,44.2);


(lib.Symbol42 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#24C8DD").s().p("AttDdIAAm5IbbAAIAAG5g");
	this.shape.setTransform(-22.7,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-110.5,-22.1,175.8,44.2);


(lib.Symbol41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_29 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(29).call(this.frame_29).wait(1));

	// Layer 2
	this.instance = new lib.Symbol46();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(29));

	// Layer 3
	this.instance_1 = new lib.Symbol46();
	this.instance_1.setTransform(0,0,6.486,6.486);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).to({scaleX:0.87,scaleY:0.87},8).to({scaleX:1,scaleY:1},4).to({scaleX:0.95,scaleY:0.95},2).to({scaleX:1,scaleY:1},2).wait(13));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-147.2,-29.1,294.5,58.3);


(lib.Symbol31 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_40 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(40).call(this.frame_40).wait(1));

	// Layer 6
	this.instance = new lib.Symbol35();
	this.instance.setTransform(-0.2,39.6);

	this.instance_1 = new lib.Symbol34();
	this.instance_1.setTransform(0.4,11);

	this.instance_2 = new lib.Symbol33();
	this.instance_2.setTransform(0,-13.9);

	this.instance_3 = new lib.Symbol32();
	this.instance_3.setTransform(0.3,-41.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).to({state:[]},1).wait(40));

	// Layer 5
	this.instance_4 = new lib.Symbol35();
	this.instance_4.setTransform(-0.2,26);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(10).to({_off:false},0).to({y:47.6,alpha:1},6).to({y:39.6},5).wait(20));

	// Layer 4
	this.instance_5 = new lib.Symbol34();
	this.instance_5.setTransform(0.4,-2.6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(7).to({_off:false},0).to({y:19,alpha:1},6).to({y:11},5).wait(23));

	// Layer 3
	this.instance_6 = new lib.Symbol33();
	this.instance_6.setTransform(0,-27.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(4).to({_off:false},0).to({y:-5.9,alpha:1},6).to({y:-13.9},5).wait(26));

	// Layer 1
	this.instance_7 = new lib.Symbol32();
	this.instance_7.setTransform(0.3,-55.4);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({_off:false},0).to({y:-33.8,alpha:1},6).to({y:-41.8},5).wait(29));

	// Layer 7
	this.instance_8 = new lib.Symbol16();
	this.instance_8.setTransform(0,60.8,0.04,0.04);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({scaleX:1,scaleY:1,y:0},10,cjs.Ease.get(1)).wait(31));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-97.5,-56.1,195,140.9);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_99 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(99).call(this.frame_99).wait(1));

	// Layer 4
	this.instance = new lib.Symbol28();
	this.instance.setTransform(324.7,-181.1,0.442,0.638,0,0,0,-0.1,0);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(89).to({_off:false},0).wait(11));

	// Layer 5
	this.instance_1 = new lib.Symbol28();
	this.instance_1.setTransform(301.8,-181.1,0.356,0.638,0,0,0,-0.3,0);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(79).to({_off:false},0).wait(21));

	// Layer 6
	this.instance_2 = new lib.Symbol28();
	this.instance_2.setTransform(342.4,-187.5,1.978,0.638,0,0,0,-0.1,0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(69).to({_off:false},0).wait(31));

	// Layer 7
	this.instance_3 = new lib.Symbol28();
	this.instance_3.setTransform(314.4,-193.8,0.857,0.638);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(59).to({_off:false},0).wait(41));

	// Layer 8
	this.instance_4 = new lib.Symbol28();
	this.instance_4.setTransform(314.4,-200,0.857,0.638);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(49).to({_off:false},0).wait(51));

	// Layer 9
	this.instance_5 = new lib.Symbol28();
	this.instance_5.setTransform(314.4,-206.4,0.857,0.638);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},0).wait(61));

	// Layer 10
	this.instance_6 = new lib.Symbol28();
	this.instance_6.setTransform(370.8,-212.6,0.877,0.638);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(29).to({_off:false},0).wait(71));

	// Layer 11
	this.instance_7 = new lib.Symbol28();
	this.instance_7.setTransform(319,-212.6,1.038,0.638);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(19).to({_off:false},0).wait(81));

	// Layer 12
	this.instance_8 = new lib.Symbol28();
	this.instance_8.setTransform(360.4,-219,1.292,0.638,0,0,0,-0.1,0);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(9).to({_off:false},0).wait(91));

	// Layer 13
	this.instance_9 = new lib.Symbol28();
	this.instance_9.setTransform(308.9,-219,0.638,0.638);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(100));

	// Layer 2
	this.instance_10 = new lib.Symbol26();
	this.instance_10.setTransform(334.7,-200.8,0.691,0.691,0,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(100));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#050505").s().p("AgIASIgIgGIgCgCIgCgDQgBgDAAgEQAAgJAEgFQAGgHALgBQANAAAFAKQAFAEAAAIIgCAGQAAAFgGAFQgHAHgIgBQgDABgFgFgAAIAJQAEgBAEgCQABgDAAgDIAAgDQgGgGgHgBIgGAAQgKABgEAGIgBADQABADABADIAHADQADgFAFAAQAFAAADAFg");
	this.shape.setTransform(231.3,-166.4,4.216,4.216);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#070707").s().p("AgDAOQgQgDgDgLQgCgEgCAAIgCgBIAAgEIAEAAIARgDQAKgCALABQAOABABABIAAAFQgBAAAAABQgBAAAAABQgBAAAAAAQAAABAAAAQgDALgGADQgFADgIAAIgHAAgAgFgKQgMACgBACQgBADABADQADAJAMADQAHABAHgCQAJgCABgKQABgGgEgBQgCgCgHAAIgJgBIgFABg");
	this.shape_1.setTransform(243.7,-188.1,4.216,4.216);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#070707").s().p("AgRALQgDgCgFgMIgDgDIAAgFIAPgCQALgBAKACIAVADIAAAEIgDABQgBAAgCAEQgDALgQADIgHAAQgIAAgGgDgAgIgKQgHAAgCACQgEACABAFQABAKAJACQAGACAHgBQANgDADgJQABgDgBgDQgBgDgNgBIgFgBIgIABg");
	this.shape_2.setTransform(218.7,-188.1,4.216,4.216);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#050505").s().p("Ag2A4QAAgLgFgBQgGgDgFgIQgGgKACgJQADgLAPgcQADgIAJgIQAIgKAJgBQAdgJAOAHIAeAPIAGACQAFACAEAEQAFAFAFAOQAEAPAAAVQABAPgIAEQgFACgBAFIgBADIgDACIADgWQAAgMgGgIQgEgFgHgHQgJgDgHgDIgCAAIgLAGQgOAIgNAFIgoAJIAAAUQgBAIADAHg");
	this.shape_3.setTransform(230,-210.5,4.216,4.216);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F0D0AC").s().p("AgahFQAdAAANASQARAWgJAjQgCAGgBAUQgDARgQAKQgMAKgQABg");
	this.shape_4.setTransform(242.8,-190.9,4.216,4.216);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E0BD9B").s().p("AAbBGQgPAAgMgKQgRgLgDgRQgCgUgBgGQgKgjARgWQAOgSAdAAIABAAIAACLg");
	this.shape_5.setTransform(219.4,-190.9,4.216,4.216);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BF9880").s().p("AgGAJIAAgDIADgDIACgDIgCgDQAAgCACgDIACgBQADAAACADQABACAAAEQgBABgCACIgEAGIgEABIgCgBg");
	this.shape_6.setTransform(259,-186.3,4.216,4.216);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DEB69A").s().p("AglBNIAAiZIABAAQAnAAANAeQAJAUgDAiQADgGAHACQAGACAAAJQgBANgSAFQgDAUgRANQgQALgTAAg");
	this.shape_7.setTransform(247.2,-194.1,4.216,4.216);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BF9880").s().p("AABAJIgEgGQgCgCgBgBQAAgEABgCQACgDADAAIACABQACADAAACIgCADIACADIADADIAAADIgCABIgEgBg");
	this.shape_8.setTransform(203.5,-186.3,4.216,4.216);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#D2A688").s().p("AAlBNQgSAAgRgLQgRgNgDgUQgSgFgBgNQAAgJAGgCQAHgCADAGQgDgiAJgUQANgeAnAAIABAAIAACZg");
	this.shape_9.setTransform(215.3,-194.1,4.216,4.216);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#B02D25").s().p("AAABgQgQAAgRgDQgSgCAAgCIABAAQAAgIABgDIAAgBIAFgOQgBgFABgEIAAgBIABAAIAAgDIABgDIABgBIACgLIgBgiIgKgZIgBgEIgLAAIgHgCQAAgsAjgTIAHgCIABAAIAaAnIAcgnIABAAIAHADQAiARAAAtIgHACIgMAAIgCAHQgFASgDAEIgBAeIgBADIABAAIADAMIABABIABADIAAADIABABQABAEgBAFIAEAOIAAABQACADABAIIAAAAQAAADgzAEg");
	this.shape_10.setTransform(231.5,-117,4.216,4.216);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#050505").s().p("AAFCjIABgHIgBgEIABgCIABgCIgBgIIAAgEIACgKQAAg8gCgMQgChOgBgMQgCgTAAgnIAAgLIgBAAIAAAMQAAAsgCANQgBALgDCVIAAAIIACAEQABAEgBAEIABAGIAAACIgCAEIABAGQgSAFgHAAIgLgDIABgLIAAgBIACgHQgCgEABgEIABgEIgBgIIgCgTQgJgiABgSQABgOADgOIgBgTIgCgVIgEgZQgDgPgBgWQgCgbABgNIAAgBIAEgVIAAgCQAAgFACgGIAAAAIAEgMIAAAAIABgBIAAgBIAAAAIBbAAIABACIAEAMIAAAAQACAEAAAHIAAACIADAQIABAFIAAABQACAZgGA0IgFAZIgCAVQgBAPABAEIADAcQABAVgJAfIgCAVIACAJIgBADQgBAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQABACgCAFQAAACACADIAAABIgBAEIACAHIgJACg");
	this.shape_11.setTransform(231.9,-17.5,4.216,4.216);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0B0C0C").s().p("AAAAYQgJgBgFgEQgEgDgBgJIAAgHIgEgDIABgHIABgHIgBgDIABgDIAPAAQAHAAAGADIADABIgBAEIAHAPQABAEAGAIQAEAHgIADQgIACgIAAIgDAAg");
	this.shape_12.setTransform(244.3,56.2,4.216,4.216);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1A1B1B").s().p("AAAAaQgJgBgFgEQgFgEgBgJIAAgIIgDgEIABgIIABgGIARgHQAEAAAHACIADACIgCAFIAHAQQABAEAIAKQAAAHgFACQgHADgIAAIgEAAg");
	this.shape_13.setTransform(244.2,57,4.216,4.216);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0B0C0C").s().p("AgSAWQgIgDAEgHQAHgIABgEIAEgIIABgMIADgBQAFgCAGAAIATAAIAAACIgCAEIABAGQACAGgBACIgDADQABAOgHAFQgFAEgJABIgDAAQgIAAgIgCg");
	this.shape_14.setTransform(219.4,56.2,4.216,4.216);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#1A1B1B").s().p("AgSAXQgDgBgCgEIgBgEQAJgKABgEQAAgCAEgHIAAgIQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIADgCQAGgCAFAAIATAAIAAADIgCAEIABAGQACAHgBABIgEAEQACAPgHAGQgFAEgJABIgEAAQgHAAgIgDg");
	this.shape_15.setTransform(219.3,57,4.216,4.216);

	this.instance_11 = new lib.Path();
	this.instance_11.setTransform(232,-162.4,4.216,4.216,0,0,0,1.5,1.1);
	this.instance_11.alpha = 0.699;

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#EFD0AC").s().p("AiIFAIAAp/IBCCUIACBdIAIA7QALA3AXAAIBQAqQBTBMAACkIgHACg");
	this.shape_16.setTransform(244.7,-158.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#E0BC9A").s().p("AiBFAIgGgCQAAikBShMQAqgmAmgEQATAAAPgzIAGgsIAAgTQAEgeAAg/IBBiUIAAJ/g");
	this.shape_17.setTransform(217.3,-158.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#EFD0AC").s().p("AgYBsIAAjVQAIgCAGABQAEgBAGABQAMACAEAIQAGAQADAhIAAACIgDALQgEARgDAGIgCAfIAFAQIABACIAAADQACADgBAFIgBACQgBAGgDADQgCADgHAEIgFADIgBABIAAABIgBABIgMAaIgEAGIgDACIgBAAIAAABg");
	this.shape_18.setTransform(242.3,-108.4,4.216,4.216);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#E0BC9A").s().p("AAXBrIAAAAIgBAAIgCgBIgFgIIgMgaIgBgBIgBAAIgBgCIgEgCQgHgEgCgDQgDgEgBgGIgBgBQgBgFACgEIAAgCIABgCIAEgQIgBgfQgEgJgGgSIgCgHIAAgFQAFghAGgNQADgIALgCQAKgCANADIADgBIAADVg");
	this.shape_19.setTransform(220.2,-108.4,4.216,4.216);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#EFD0AC").s().p("AAAC2QgJgBgGgEQgEgDgBgJIAAgIIgDgEIABgHIAEgNIABgFQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIgBgwIgCglIABgXIABgQIgGgzIgCg7IAAgPQAEgBADgGIAFgLQAGgMAFgEIAEgEQAIgEADgFIAEgIIAEAOIAAAAQACAEAAAHIAAABIAEAWQADAXgHA2IgFAdIgEAYIACAOIADAaQABATgIAeQgHAaACAJIACAUIAHARQABAEAHAIQAEAHgIADQgIACgIAAIgDAAg");
	this.shape_20.setTransform(243.9,-10.4,4.216,4.216);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#E0BC9A").s().p("AgSC0QgJgDAFgHQAHgIAAgEIAEgKIAEgHIABgGIAAgOQACgJgHgaQgIgeABgTIADgYIABgBIACgPIgEgYIgFgdQgHgzACgaIABgBIAEgVIAAgBQAAgHABgEIAAAAIAFgOIAEAIQADAFAHAEIAFAEQAEAEAHAMIAFALQACAGAFABIAAAQQgBAvgCALIgGAzIACANIABAaIgDAlIgBAwQABAAAAABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIAGARQABAGAAACIgEAEQACAPgHAFQgFAEgKABIgCAAQgIAAgIgCg");
	this.shape_21.setTransform(219,-10.4,4.216,4.216);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#E0BC9A").s().p("AgFB2QgMgEgEggIgBgMQAAgSACghIACgcQAAhDAUgbQAKgOALAAIgQA0QAFAigBAHQgEAPgHAJIAAAMIACAcQAAADgFAaQgBAFABADIABAGQACAFAJASQABADgBADQgCADgFACIgEABIgDAAg");
	this.shape_22.setTransform(209.3,-104.6,4.216,4.216);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#EFD0AC").s().p("AgBB1QgFgCgBgDQgCgDACgDQAJgTACgGIABgEQABgDgBgEIgGgeIABgcIAAgMQgFgJgEgPQgBgEACgTIACgSIgQg0IAHACQAIADAHAJQATAbAABDIACAcQACAiAAASIgBALQgEAhgMADIgDAAIgEgBg");
	this.shape_23.setTransform(253.1,-104.8,4.216,4.216);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#FFFFFF","#000000"],[0,1],-4.5,0,0.4,0).s().p("AAAAAIAAAAIAAAAIABAAg");
	this.shape_24.setTransform(230.8,-63,4.216,4.216);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.instance_11},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(198,-235.2,204.3,303.5);


(lib.Symbol18 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FBA625").s().p("AgcBNIADiZIAyAAIAECZg");
	this.shape.setTransform(-9.9,-94.2,0.493,0.493);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#35475B").s().p("AlQA1IgChqIKjABIACBqg");
	this.shape_1.setTransform(8.2,-91.5,0.493,0.493);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#4B637F").s().p("AlOBsIgFjYIKiABIAGDYg");
	this.shape_2.setTransform(8.1,-94.2,0.493,0.493);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#35475B").s().p("AEEBsIgFi9IogAdIgBgaII/gdIAGDXg");
	this.shape_3.setTransform(8.4,-96.9,0.493,0.493);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AmnBuILHm2ICIDbIrHG3g");
	this.shape_4.setTransform(-13.5,-38.3,0.493,0.493);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FED6B7").s().p("AEyKMQi8gehpijQgzhSgdhJIgjhsQgTg5gggtQgpg8hUhNIlzlYQgugrgIg9QgHg9AmgwQAngxA/gHQA+gGAxAnIIZH0QBhgQBtALQB7AMBuAtQBZAkAxBYQArBRAGBsQAFBlgdBdQgeBdg1AxQg2AwhNAUQguAMgwAAQggAAgigGg");
	this.shape_5.setTransform(-43.7,-66.1,0.493,0.493);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FED6B7").s().p("Al6AbIIAmVID1GWIorFfg");
	this.shape_6.setTransform(-19,-51.5,0.493,0.493);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#35475B").s().p("AxyAlIABhMMAjiAAEIACBLg");
	this.shape_7.setTransform(-36.8,-92.4,0.493,0.493);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#4B637F").s().p("AxyBMIACiZMAjfAADIAECYg");
	this.shape_8.setTransform(-36.8,-94.3,0.493,0.493);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FBA625").s().p("Ag+ARQAKgRgJgTIB8ghIgDBpg");
	this.shape_9.setTransform(-93.8,-94.7,0.493,0.493);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#3093D9").s().p("Ag/ANQgSgGABgHQAAgKARgDICRgnIgEBpg");
	this.shape_10.setTransform(-94.7,-94.7,0.493,0.493);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FED6B7").s().p("AjJD2QjljzC9AiQDCAigBjrQAAiFg8jFQEHA3BxECQA4CCAEB0IkIGtQiXh/hyh5g");
	this.shape_11.setTransform(-29,-74.5,0.493,0.493);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FED6B7").s().p("Al0DgQgxgWgTgyQgSgyAWgxQAWgyAygPIJ/jXQAygRAxAVQAwAWATAxQASAygWAxQgWAxgyAQIp/DYQgWAIgWAAQgbAAgbgMg");
	this.shape_12.setTransform(-64.6,-104.5,0.493,0.493);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FED6B7").s().p("ADhDIIoTidQgzgPgYgvQgYgxARgzQARgyAwgXQAvgYA0AQIITCdQAzAPAYAvQAXAxgRAzQgRAygvAYQgcAOgeAAQgUAAgVgHg");
	this.shape_13.setTransform(-34.4,-105.9,0.493,0.493);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FED6B7").s().p("AAHIhQg0gXgIgyIiEtUQgJg4ASgsQATgwAvgSQAygTAxAWQAvAWASAyICENUQAJA4gRAsQgUAwgvASQgZAJgYAAQgcAAgbgLg");
	this.shape_14.setTransform(-17.4,-80.9,0.493,0.493);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#D3B094").s().p("AkpFmQgqghgGg2QgHg2AigoIG0oBQAigpA1gGQA0gHAqAhQAqAhAGA1QAGA1ghAqIm0ICQgiApg0AGIgSABQgqAAgjgcg");
	this.shape_15.setTransform(-44.5,-79.5,0.493,0.493);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#D3B094").s().p("ApLkXIFvjpIKOCKICaMzIm4BEg");
	this.shape_16.setTransform(-43.2,-82.3,0.493,0.493);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#D3B094").s().p("AksE7Qg0gIgfgrQgggsAJg1QAIg2AsgdIIvl4QAsgeA0AIQA1AJAfArQAfArgJA1QgIA1grAfIovF3QgjAYgnAAQgLAAgMgCg");
	this.shape_17.setTransform(-51.9,-84.2,0.493,0.493);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#D3B094").s().p("AlaEHQgzgRgXgvQgYgwAQgzQARg0AwgWIJkkaQAxgWAyAQQAyARAYAvQAYAvgRAzQgRAzgwAYIpjEZQgdAOgdAAQgUAAgVgHg");
	this.shape_18.setTransform(-60.5,-90.6,0.493,0.493);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#656565").s().p("AwNyyIGrkIMAZxAptImsEIg");
	this.shape_19.setTransform(41.2,26.5,0.493,0.493);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#4C4C4C").s().p("AzjwuINXoQMAZwAptItXIQg");
	this.shape_20.setTransform(30.6,33,0.493,0.493);

	this.instance = new lib.Path_21();
	this.instance.setTransform(3.8,1.8,0.493,0.493,0,0,0,195,230.2);
	this.instance.alpha = 0.199;

	this.addChild(this.instance,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-98.8,-116.2,197.6,232.5);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#DEDEDE").s().p("AAsARIgBgEIgLAAIgGgNIAAgIIgEgGIgCgDIAGADQAGADAEADIAEACQALAHAEAOIACACgAg4ARIALgOIAHgEIAFgGIABgBIADAAIABgBIABgBIAAAAIABgBIAHgDIAEgDIAAAAIgBADIgEAGIAAAGIgIAPIgJAAIAAAEg");
	this.shape.setTransform(14.5,-26.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FCFCFC").s().p("AASASIgCgCQgCgCgHgDIgCAHIgIAAIgCgHQgIADgCACIgCACIgBAAIAAgBQgEgOgBgEIABgGIAEgGIABgDIABgBQAAACAEALIALANIABAAIACAAIAEgHIAHgGIAEgNIAAAAIABABIABADIAEAGIAAAHIgBAEIgDANIAAABg");
	this.shape_1.setTransform(14.7,-26.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B36F6F").s().p("AgEAAIgDgBIAGABIABgBIACABIAGgBQgEACgEAAQgBAAgDgBg");
	this.shape_2.setTransform(14.8,-30.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#C07773").s().p("AAAAAIAAABIgHgBIAAAAIAHAAIAAAAQAAAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAIAGAAIgGABIgCgBg");
	this.shape_3.setTransform(14.8,-30.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#DBC4A1").s().p("AATAuQgJAAgIgDIgGgEIgCgBIgBgCQgIgGgDgIQAAggAXgZIAOgKIAABKIgCgBIgHACIAAAAIADACQADACADAAIAAAMg");
	this.shape_4.setTransform(12.9,-33.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgkBBQgQgKgJgVQgRgmAigvQARgVAYAAQAJgBAIAGIAVAGQAVAIAEARIAGAYQADAMgCAJQgDAagJAQQgFAJgDADIgMAJIACgFIgCAAIgHAEIgGgDIgBgCIAAABIgBgEIgBgDIAHgEIACgBIABgBIADgCQAIgFAEgHIABgDQABgKgBgKIgCgHQgDgKgQgMQgGgFgCgLIgBgKIgLAJIgMAKQgZAXAAAiIAAACIAAADQAEAFAGAEIACACIACABIAIAEIAAABIAAAEIgBACIgBACIgBAAIgEADIgIgEIACAGg");
	this.shape_5.setTransform(14.4,-35.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BB9E82").s().p("AgMAAIgDgCIABgBQAIADAGAAIAAAAQAIAAAIgCIAAAAIgDACQgFAEgIAAQgHAAgFgEg");
	this.shape_6.setTransform(14.7,-28.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#DBC49F").s().p("AABAWIADgDQACgCAHgCIACAHgAgTAWIAAgFIAJAAIAIgRQAAAHACANIAAACgAASAMIgLgNQgEgKAAgDIABgDIAAgEIACACQAFAGAJAAIAAAZg");
	this.shape_7.setTransform(12.7,-27);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#D8BE9F").s().p("AAFAAIABgNIABgEQABAKgBAIIgBADQgEAHgGAFIgDACQAKgIACgKg");
	this.shape_8.setTransform(18.2,-31.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#35475B").s().p("AkCDuIIGgCIAAAoIoGABgAkDAMIIGgCIAAAnIoFACgAkDkUIEDAAIAABOIkDAAg");
	this.shape_9.setTransform(-0.3,-12.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#ECD8B4").s().p("AAABHIAAgBIABgNIABgFIAGAPIALAAIACAEgAgPBHIADgHQAHADACACIACACgAgTA+IAAgbQAIAAAFgFIADgDIAAAAQgIACgIAAIAAgMQAFAAADgEIgGgCQAAAAgBAAQAAAAAAAAQgBAAAAABQAAAAAAAAIAAhKIALgJIABAKQACAMAFAEQAPAMADAMIACAHIgBAFIgBAKQgCAMgMAIIAAABIgDABIgEAEIAAADIABAEIgFANIgGAIIgFAHg");
	this.shape_10.setTransform(16.9,-31.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#CBAC8B").s().p("AgDgBIgBgCIAAgCQADAFAGAGQgFgDgDgEg");
	this.shape_11.setTransform(11.4,-30.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CBCBCB").s().p("Aj7EfIIFgBIAAASIoFACgAj7EBIIFgCIAAASIoFACgAj7DiIIFgCIAAATIoFABgAj8DEIIGgDIAAATIoGACgAj7CkIIFgBIAAATIoGABgAhAA9ICngBIAAASIinACgAj5A9ICogBIAAASIioACgAhAAfICngCIAAASIinACgAj5AfICogCIAAASIioACgAhAAAICnAAIAAAQIinACgAj6AAICpAAIAAAQIioACgAhAgdICngBIAAASIinACgAj6gdICpgBIAAASIipACgAhAg7ICngCIAAASIinACgAj6g7ICpgCIAAASIipACgAj7i2ID2AAIAKAAID/AAIACASIoBABgAj8jUIDqAAIAWAAID/gBIABATIoAABgAj8jzID3AAIAJAAID/AAIAAASIn/ABgAj+kAIAAgRIDigBIAcAAIAAASIkJABgAj+keIAAgSID+gBIAAATIkJAAg");
	this.shape_12.setTransform(-0.9,0.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ak6m6IJygBIABFwIABAAIABIFIpyACgAkFEkIAAATIIGgCIAAgSgAkEEGIAAASIIEgCIAAgSgAkFDnIABASIIEgBIAAgTgAkFDJIAAASIIFgCIAAgTgAkFCpIAAATIIFgBIAAgTgAkFBvIAAAnIIFgBIAAgngAhJBCIAAATICmgCIAAgSgAkDBCIAAATICogCIAAgSgAhJAkIAAASICmgCIAAgSgAkDAkIAAASICogCIAAgSgAhKAFIABASICmgCIAAgSgAkEAFIABASICogCIAAgSgAhKgYIAAATICngCIAAgSgAkEgYIAAATICpgCIAAgSgAhKg2IAAASICngCIAAgSgAkEg2IAAASICpgCIAAgSgAkGhwIAAAmIIFgBIABgngAkGieIABAAIIBgBIgBgSIj+AAIAAAAIgMAAIj2AAIgBAAgAkGi8IAAAAIIBgBIgBgTIj9ABIAAgBIgYABIjrAAIAAAAgAkGjbIAAAAIIAgBIAAgSIj9AAIAAAAIgMAAIj3AAIAAAAgABzkTIgCABIgCABIgBABIgGAFIgGAHIgLAOIASAAIAWAAIABAAIAOAAIAKAAIANAAIABAAIAXAAIANAAIgCgDQgEgOgLgIIgEgCQgEgEgGgCIAIgEIABAAIgCAFIAMgJQAEgDAEgJQAJgQADgaQACgLgCgMIgHgYQgDgRgWgIIgUgGQgIgGgLABQgZAAgQAVQgiAvARAoQAJAVAPAKIANAIIgDgGIAIAEIgGADIgBABIgBAAgAgmkNIjhABIAAARIgMABIELgBIAAgSIgeAAgAkHkrIAAASIgMAAIELAAIAAgTgAkHmSIABBNIEDAAIgBhOg");

	// Layer 2
	this.instance = new lib.Symbol15();
	this.instance.setTransform(1.8,1.6);

	this.addChild(this.instance,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.5,-44.5,64.9,90.6);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A41117").s().p("AAEADIgCgBIgBgBIgBAAIAAAAIAAABIgCABQgFACgBAAIAAgDIAAgCIAAgBIAAAAIAAgDIAGACIACACIAAgBIABABIADgCIAFgCQAAAAAAABQABAAAAABQAAAAgBABQAAABAAAAIAAAAQABAEgBABIAAAAIgFgCg");
	this.shape.setTransform(18.5,6.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EBD8B4").s().p("AAAAAIABAAIgBABg");
	this.shape_1.setTransform(18.8,6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BB9E82").s().p("AABACQgEAAgEgDQAFABADAAIAHAAIgDABIgDABg");
	this.shape_2.setTransform(18.4,5.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#DBC49F").s().p("AgEgDIAAAAIAAAAQAEADAEAAIABAAIAAADIgCABg");
	this.shape_3.setTransform(18.1,5.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F5F6F6").s().p("AAAARIAAgPIgBgCIABAAIAAAAIABAAIABAAIAAACIgBAEIAAALgAATAAIgBgCQgEgCgDACIgCABQAAgBAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAIgFACIgDACIgBAAIAAAAIgDgCIgFgCIgBADIAAABIgCAAQgDgCgDADIgBAAIgBABIAAAAIAAgEIAAgCIAEgFIADgFIABABIADADIAIAJIABgCIADgDIADgDIADgCIAEgCIAGAJIAAACIAAACIAAACg");
	this.shape_4.setTransform(18.5,6.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E5E5E5").s().p("AAdAKIABgFQABgFADAAQAEAEADAGgAABAKIAAgKIABgDIAAgCIACABQAEADABgBQABAAgBgFIAAgBIACgBQADgBAEABIABACIgLARgAgGAKIgLgSIAAAAQADgCADABIADAAIAAACIAAACIAAADQABABAFgDIACgBIAAADIAAAMgAgoAKQADgIAFgEIgBABQADABACAFIABAFg");
	this.shape_5.setTransform(18.5,7.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#010400").s().p("AAHALIAMgRIABACIAAgEIAAgCQAJADAEAHIABAAQgDABgBAEIgBAGgAgcALIgBgGQgBgEgDgBIABgBIAAgBQAEgFAJgDIAAAGIAAgBIABgCIAMASg");
	this.shape_6.setTransform(18.5,7.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#D8BE9F").s().p("AgQAWIAFgDQAKgHABgMIABgPIABgEIABADQAAABAAABQAAABABABQAAAAAAAAQAAAAABAAIABgEQABgDADgCIABgBIADABQAEABAAAGQgBAIgMAEQgCALgLAJIgJAFIABgBg");
	this.shape_7.setTransform(21.9,2.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#35475B").s().p("AkCDuIIGgBIAAAmIoGACgAkDANIIGgCIAAAmIoFACgAkDkTIAbAAIC8gBIAACPIjXABg");
	this.shape_8.setTransform(-0.3,-12.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CBAC8B").s().p("AABAjQgKgJgDgNQgLgEgBgIQgBgEAFgBQADgCACACIABABIAAABIABAAIABACIABADQACAAgBgPQgCgTALgGQADgCAGABQAGABAGAEQACACADAAIAABDIgBAAQgOgBgBgJQAAgBAAAAQAAAAAAAAQAAAAAAABQAAABgBAAQgBAEABAEQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAQgFgBgEgDg");
	this.shape_9.setTransform(16,1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#ECD8B4").s().p("AAAAjIAAgIQgBgBAAAAQAAgBAAAAQAAAAgBAAQAAAAAAABQAAAJgOABIgBAAIAAhDIAEgBIAKgFQAJgDAHAMQAGAKgCAIIAAAIIgBACIgCARQgCAMgLAHIgCADIABgEg");
	this.shape_10.setTransform(20.4,1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0E0E0E").s().p("AgNA6IgBAAIgDgCIAAgCIgBAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgFABgDQAAgBAAgBQAAAAAAAAQAAgBAAABQABAAAAAAQAAAKAOABIACAAIAAAAQAMgBAAgKQAAAAABAAQAAgBAAABQAAAAAAAAQABABAAABIAAAIIgBADIgBABIgBABIgEADIgDABIgFACQgFAAgFgDgAAgAOIgBgEIABgIQABgFgGgKQgGgMgMADIgJAFIgCAAQgEAAgCgCQgGgEgFgBQgHgBgEADQgLAGABARQABARgCgBIgBgCIgBgEIgBAAIAAgBIgBgBIgDgIQgDgGAAgHQAAgQAOgNQAFgGAKgFIAIgEIgEAEIABgBQAFgDAHgDQAIgDAGAEIgDAAIgEABQAFgCAJAEQAHADAGAHQAGAHAFACQAJADADgEQgEAHgHAAIgCAAIACAEIABAJIAAAJIgBAKIgBAGIgCABQgDACAAACIgBAFIgBAAQAAAAAAgBQAAAAgBAAQAAgBAAgBQAAAAAAgBg");
	this.shape_11.setTransform(19,-0.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#CBCBCB").s().p("AkCEvIIGgBIAAASIoGACgAkBERIIEgCIAAASIoEACgAkCDyIIFgCIAAATIoEABgAkCDUIIFgDIAAATIoFACgAkCC0IIFgBIAAATIoFABgAhGBNICmgBIAAASIimACgAkABNICogBIAAASIioACgAhGAvICmgCIAAASIimACgAkAAvICogCIAAASIioACgAhHAQICngCIAAASIimACgAkBAQICpgCIAAASIioACgAhHgNICngBIAAAQIinACgAkBgNICpgBIAAAQIipACgAhHgrICngCIAAASIinACgAkBgrICpgCIAAASIipACgAkCimID2AAIAMAAID+AAIABASIoBABgAkDjEIDrAAIAYAAID9gBIABATIoBABgAkDjjID3AAIAMAAID9AAIAAASIoAABgAAAjwIAAgRID9gBIAAASIkJABgAAAkOIAAgTID9AAIAAATIkJAAgAAAkuIAAgSID9gBIAAATIkJAAg");
	this.shape_12.setTransform(-0.3,-1.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ak6m6IJygBIADN1IpyACgAkFEkIAAATIIGgCIAAgSgAkEEGIAAASIIEgCIAAgSgAkFDnIABASIIEgBIAAgTgAkFDJIAAASIIFgCIAAgTgAkFCpIAAATIIFgBIAAgTgAkFBvIAAAnIIFgBIAAgngAhJBCIAAATICmgCIAAgSgAkDBCIAAATICogCIAAgSgACKADQgFACABAGQABAIALADQADAOAMAIQAEADAFACIAAAAIgDAFIgEAGIAAABQgIADgEAGIAAAAQgGAGgDAIIANAAIAVAAIAHAAIACAAIAHAAIAVAAIAMAAQgDgGgEgGIAAgBQgFgHgIgDIgBgCIgFgJIABgBIAJgFQAMgIADgOQAMgDAAgIQABgGgFgCIgDAAIABgEIACgMIAAgJIgCgJIgBgEIABAAQAIAAAEgHQgDAEgKgDQgEgCgGgHQgGgHgHgDQgJgEgFACIAEgBIADAAQgGgEgKADQgIADgEADIgBABIAEgEIgIAEQgKAFgGAGQgNANAAAQQAAAHACAIIAEAGIgDgBIgCAAgAhJAkIAAASICmgCIAAgSgAkDAkIAAASICogCIAAgSgAhKAFIABASICmgCIAAgSgAkEAFIABASICogCIAAgSgAhKgYIAAATICngCIAAgSgAkEgYIAAATICpgCIAAgSgAhKg2IAAASICngCIAAgSgAkEg2IAAASICpgCIAAgSgAkGhwIAAAmIIFgBIABgngAkGieIABAAIIBgBIgBgSIj+AAIAAAAIgMAAIj2AAIgBAAgAkGi8IAAAAIIBgBIgBgTIj9ABIAAgBIgYABIjrAAIAAAAgAkGjbIAAAAIIAgBIAAgSIj9AAIAAAAIgMAAIj3AAIAAAAgAgDkMIAAARIgMABIEJgBIAAgSgAkHmSIAACPIDYgBIgBiPIi8ABIgbAAgAgDksIAAATIgMAAIEJAAIAAgTgAgDlLIAAASIgMAAIEJAAIAAgTgACrAzIADACIAAAAg");

	// Layer 1
	this.instance = new lib.Symbol15();
	this.instance.setTransform(1.8,1.6);

	this.addChild(this.instance,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.5,-44.4,64.9,90.6);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1D2250").s().p("AgFADIAAAAIABgKIAAgCQAEgGAAAAIAFAGIAAABIABAMIgGAMg");
	this.shape.setTransform(13.4,-18.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E0BC9A").s().p("AAGAPIABAAIADAIIAAAAgAAFgCIgFgQIAAgBIABgDIACAAQAGAHAJAAIAAASIgBAAQgBgCgLgDgAgPgEIAEAAIgFABIABgBgAgFgGIABgBIgBABIgBAAg");
	this.shape_1.setTransform(11.6,-20.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BF9880").s().p("AAAADQgIAAgGgFIAIABIACABIAEAAIAAAAQAHAAAIgCQgFAFgKAAg");
	this.shape_2.setTransform(13.5,-22.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F8F8F8").s().p("AgSAUIgDgPQgDgKACgFIAAAAIADgGIADgGIAAABIAFAQQALAFAAAAIAAAAIAFgCIAHgDQAEgOAAgDIABAAIACAGIAEAGIAAAAIABAAIAAABQABAEgCAKIgEAPIgBADIgCgFIgGgGIgEAJIgBgOIAAgBIgFgGQAAAAgEAGIAAACIgBAMIgEgIIgBAAIgFAGIgCAFIAAAAIgBgDg");
	this.shape_3.setTransform(13.4,-20.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#111011").s().p("AhIAbIAFgNQAJgYATgKIAFgCIAFgCIAFgCIACAAQgCAEADANIADANQAAABAAAAQAAABAAAAQAAAAABAAQAAAAAAAAIACgEIAFgFIAFAHIAFAMIAGgMIAEgGIAGAEIACAEIABgCIAEgNQACgNgBgEIAEABIABABIAGACIAFACQATAKAJAYIAFANg");
	this.shape_4.setTransform(13.4,-18.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#EFD0AC").s().p("AgQgFIAAAAQALAAAFgHIAAAAIAAADIAAABIAAgBQAAAEgEALIgHAEIgFADgAAMAEIACAAIADACgAAGACIAAAAIAAAAIAAgBIABABIADABg");
	this.shape_5.setTransform(15.2,-21.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#D2A688").s().p("AAhBOIgCgBIgIgBIgCgBQgJgDgKgGQgQgNgEgUQgSgFAAgMQgBgKAHgCIAEAAQADAAADAEQgDgiAIgUQANgfAiAAIAFCbIgEAAg");
	this.shape_6.setTransform(9.6,-30.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#7A522D").s().p("AA5gBQgNgfgpAAIgEAAQgkAAgNAfQgJARADAlQgCgFgEAAQgFgDgEgHQgGgJADgKQACgHAQggQADgHAIgJQAJgJAIgDQAegIAOAHIAfAPIAEACQAGACAEAEQAFAFAFAOQAFAPAAAVQAAAOgHAFQgEAAgCAFQADglgJgRg");
	this.shape_7.setTransform(13.1,-35.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#DEB69A").s().p("AgjBOIgFibIAGAAQAnAAAOAfQAIAUgDAiQADgEAEAAIADAAQAHACAAAKQgCAMgRAFQgEAUgSANQgIAHgKADIAAAAQgIACgIAAg");
	this.shape_8.setTransform(17,-30.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CBCBCB").s().p("AkBEfIIFgBIAAASIoFACgAkBEBIIFgCIAAASIoFACgAkBDiIIFgCIAAATIoFABgAkCDEIIGgDIAAATIoGACgAkBCkIIFgBIAAATIoGABgAhMA9IFQgBIAAASIlQACgAhMAfIFPgCIAAASIlPACgAhMAAIFPAAIAAAQIlPACgAhMgdIFPgBIAAASIlPACgAhMg7IFPgCIAAASIlPACgAkCi2IECAAIAAASIkCABgAkDjUIEDgBIAAATIkDABgAkDjzIEDAAIAAASIkDABgAkDkRIEDgBIAAASIkDABgAkDkwIEDgBIAAATIkDAAg");
	this.shape_9.setTransform(-0.3,0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#35475B").s().p("AkCDuIIGgBIAAAmIoGACgAkDANIIGgCIAAAmIoFACgAkDkTIEDgBIAABNIkDABg");
	this.shape_10.setTransform(-0.3,-12.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ak6m6IJygBIADN1IpyACgAkFEkIAAATIIGgCIAAgSgAkEEGIAAASIIEgCIAAgSgAkFDnIABASIIEgBIAAgTgAkFDJIAAASIIFgCIAAgTgAkFCpIAAATIIFgBIAAgTgAkFBvIAAAnIIFgBIAAgngAhPBCIAAATIFPgCIAAgSgAhPAkIAAASIFPgCIAAgSgAhQAFIABASIFPgCIAAgSgAhQgYIAAATIFQgCIAAgSgAhQg2IAAASIFQgCIAAgSgAkGhwIAAAmIIFgBIABgngABxjcIgDAGIgBABIgBAAIgFACIgEABIgCABIgFACQgTAKgIAaIgFANICSAAIgEgNQgJgagTgKIgGgCIgCgCIgDAAIgCgBIgDgBIgBgBIgEgGIgDgFIAAgBIAAgDQAKgDAJgGQATgOADgUQASgEABgNQABgJgHgCIgEgBQAHgFAAgOQAAgVgFgRQgFgOgFgFQgEgEgGgCIgEgCIgfgPQgOgHggAIQgIADgJAJQgIAJgDAHQgQAigCAHQgDAKAGAJQAEAHAFADIgEABQgGACAAAJQABANASAEQAEAUASAOQAJAGAKADIgBAEIAAAAIAAgBgAkGixIAAATIEEgBIgBgSgAkGjPIAAATIEDgBIAAgTgAkGjuIAAATIEDgBIAAgSgAkGkMIAAASIEDgBIAAgSgAkGkrIgBASIEEAAIAAgTgAkHmSIABBNIEDAAIgBhOg");

	// Layer 2
	this.instance = new lib.Symbol15();
	this.instance.setTransform(1.8,1.6);

	this.addChild(this.instance,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.5,-44.4,64.9,90.6);


(lib.Symbol6 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2E5A77").s().p("AhVAmIACgHIgCAHgAAhAlQAIgGAIAAQACgHgBgHQgBgGgFgJQAKgBANAFQgHgNgKgLQgHgJgHgFIAEAAQAOACAHAGQAGAGAGAPIANAogAAFAlIgFAAIAAhGIAAgBIAPALIgKAYIACAhQACgMAIgQQAEgIACgOIABgVIADACIAIAFIAKALQALALAHAKQgNgEgMACQAEAFABAFQACAFAAAJQgIABgLAMgAhIgCQAEgKAEgGIgIAPIgBADIABgCg");
	this.shape.setTransform(-17.7,-19.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#21435B").s().p("AgPAmQgLgMgIAAQgBgKACgFQACgFAFgGQgOgBgMAEQAFgJAMgOIALgLIAFgDIAAgBIAFgDIAAABQAAAJACAMIAAABQACAOAEAHIAIAgIACgkIgJgXIAOgLIAAAAIABBGIAEAAIggABgAhMAnIACgHIACgEIACgGIAGgTIABgDIABgCIAIgPIADgFQAEgEAFgBIAKgEIACAAIAGAAIgKAIQgQAPgFAPIALgDIALAAQgEAIgCAGQgBAIACAHQAIgBAIAHgAAkAmQALgMAIgBQgBgJgBgFQgBgFgFgGQANgBANAEQgHgKgLgLIgKgLIgIgFIgBgDQAFACAFAEQAHAFAGAJQALALAGANQgMgFgKABQAEAJABAGQABAHgCAHQgHAAgIAGg");
	this.shape_1.setTransform(-18.6,-19.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#142B3C").s().p("AAJAoQgJgGgFAAQgDgHACgIQABgGAEgIIgLAAIgLADQAGgPAPgPIAIgIIAFgDIgFADIgJALQgMAOgFAJQAMgEAMABQgEAGgBAGQgBAEAAAKQAHAAAKANIgDAAgAARgkIAHgDQAAAFgFASIAAACQgCgNAAgJg");
	this.shape_2.setTransform(-21.9,-19.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E5E5E5").s().p("AAAAKQgBgJgCgMIAAgBIAAgBQADgTAAgEIgFADIAAgBIgGADIAAABIgFADIAAgBIAOgNIAAABIALAHIAIAFIgPALIALAXIgCAkIgLggg");
	this.shape_3.setTransform(-19.5,-20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F6D5B2").s().p("AgBAKQgCgEgBgFQgCgEABgEQAAgBAAgBQAAAAABgBQAAAAAAgBQABAAAAgBIABgBQACAAABAEQADADABAGIABABIAAAHQgBAFgDAAIAAABQgCAAgBgEg");
	this.shape_4.setTransform(-23.3,-31.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E7C4A0").s().p("AgUACIAAgKQAKAGAFABIAHAAIAHgCIAGgCIAGgDIAAAEIgcANg");
	this.shape_5.setTransform(-17.7,-24.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#EFCDAA").s().p("AgFAuQgIgFgHgIQgMgOgFgSQADgBABgDIAAgHIABgGQAGgfAZgDIAJgCIAABpQgFgBgIgGgAAkAuIACgBIgCABg");
	this.shape_6.setTransform(-19.2,-30.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FEDCB8").s().p("AgaA/IgIgFIAegOIAAAGIgVANIAAAAIgBAAgAggg7IALAAQANAAAHgDQAIAFAHAMQAEAIAEANIABACIADgHQADgDACAAIABAAQAAABABAAQAAAAAAABQABAAAAABQAAABAAABIAAAKQgBAGgDAEQgDAEgCgBQgFAQgMAOIgBACIgHAIIgCACIgCABIAAAAIAAAFIAAgFIgGADIgGADIgHABIgJAAg");
	this.shape_7.setTransform(-15,-29.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#7C5E53").s().p("AgwAkQgBgFgDgEQgDgDgCAAIgBABQgCgUANgRQASgaAfgBQAfABASAfQAGAMACANIABAGIgBAAQgCgBgDAEIgDAHIgBgDQgEgNgEgIQgHgKgKgFQgHADgNABIgJAAIgLABQgZACgGAfIgBAGIgBgDg");
	this.shape_8.setTransform(-17.8,-35.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#CBCBCB").s().p("AkCEfIIGgBIAAASIoGACgAkBEBIIEgCIAAASIoEACgAkCDiIIFgCIAAATIoEABgAkCDEIIFgDIAAATIoFACgAkCCkIIFgBIAAATIoFABgAkCA9IIFgBIAAASIoFACgAkCAfIIEgCIABASIoFACgAkDAAIIGAAIgBAQIoEACgAkDgdIIGgBIAAASIoGACgAkDg7IIFgCIAAASIoFACgAAAi2IECAAIABASIkDABgAAAjUIECgBIAAATIkCABgAAAjzIECAAIAAASIkCABgAAAkRIECgBIAAASIkCABgAAAkwIECgBIAAATIkCAAg");
	this.shape_9.setTransform(-0.3,0.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#35475B").s().p("AkCDuIIGgBIAAAmIoGACgAkDANIIGgCIAAAmIoFACgAAAkTIECgBIAABNIkCABg");
	this.shape_10.setTransform(-0.4,-12.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ak6m6IJygBIADN1IpyACgAkFEkIAAATIIGgCIAAgSgAkEEGIAAASIIEgCIAAgSgAkFDnIABASIIEgBIAAgTgAkFDJIAAASIIFgCIAAgTgAkFCpIAAATIIFgBIAAgTgAkFBvIAAAnIIFgBIAAgngAkFBCIAAATIIFgCIAAgSgAkFAkIAAASIIFgCIgBgSgAkGAFIABASIIEgCIABgSgAkGgYIAAATIIGgCIAAgSgAkGg2IAAASIIFgCIAAgSgAkGhwIAAAmIIFgBIABgngAjajkIgKADQgFACgEADIgEAFQgEAGgEAKIgBAEIAAACIgGATIgCAGIgCAEIgCAHIAAAAIA2AAIAEAAIAiAAIAVAAIAHAAIA2AAIgOgrQgGgPgGgGQgHgGgOgBIgDAAQgFgFgFgBIAAACIgDgBIgBAVQgCAOgEAKQgHAQgDAMIgCghIAKgaIgPgLIABAAIAVgNIAAgGIAAgFIACgBIADgCIAHgIIABgCQANgOAFgSQACABADgEQACgEACgGIAAgKQgBgBAAgBQAAgBAAAAQgBgBAAAAQAAAAgBAAIgBgHQgCgNgGgNQgSgggfAAQghABgSAaQgMATABATQAAABAAAAQgBAAAAABQAAAAAAABQgBABAAABQAAAEABAGQABAFADAEQADAEABgBQAFATANAOQAHAIAHAFIABALIgBAAIgOANIAAAAIgFAAIgCABgAgCixIAAATIECgBIgBgSgAgCjPIAAATIEBgBIAAgTgAgCjuIAAATIEBgBIAAgSgAgCkMIAAASIEBgBIAAgSgAgCkrIgBASIECAAIAAgTgAgDmSIABBNIEBAAIgBhOg");

	// Layer 2
	this.instance = new lib.Symbol15();
	this.instance.setTransform(1.8,1.6);

	this.addChild(this.instance,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.6,-44.4,65,90.6);


(lib.Symbol5 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CBCBCB").s().p("Aj8FnIH/gDIAAAPIn/AEgAj8EwIH+gDIABAQIn/ADgAj9DDIH/gDIAAAPIn/ADgAj4BpIH/gDIAAAPIn/AEgAj4AyIH+gEIABARIoAACgAj5g6IH/gCIAAAPIn/ADgAkFhxIEBgCIAAAQIkAABgAkFiNIH/gCIAAAPIn+ADgAkFioIH/gDIAAAQIn/ACgAkFjDIH/gDIAAAPIn/ADgAkFjfIH+gDIABAQIn/ADgAkGj6IH/gDIABAQIn/ACgAkFkWIH/gDIAAAQIn/ADgAkGkxIH/gCIAAAPIn/ADgAkGlMIH/gDIAAAQIn+ACgAidl0IEvgCIAAAQIkwACg");
	this.shape.setTransform(0.5,2.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ak7m5IJzgDIAEN1IpyAEgAj3GAIAAAQIH/gEIAAgPgAj3FKIAAAPIH/gDIgBgQgAj4DcIAAAPIH/gCIAAgQgAjzCCIAAAQIH/gDIAAgQgAjzBLIgBAPIIAgCIgBgRgAj0ghIAAAQIH/gDIAAgPgAkAhYIABAQID/gBIAAgQgAkAh0IABARIH+gEIAAgPgAkAiPIAAAQIH/gDIAAgPgAkAiqIAAAQIH/gEIAAgPgAkAjFIAAAQIH/gEIgBgPgAkBjhIABAQIH/gDIgBgQgAkAj8IAAAQIH/gEIAAgQgAkBkXIAAAPIH/gDIAAgPgAkBkzIABAPIH+gCIAAgQgAiYlbIgBAQIEwgBIAAgRg");

	// Layer 2
	this.instance = new lib.Symbol15();
	this.instance.setTransform(1.8,1.6);

	this.addChild(this.instance,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-31.6,-44.5,65,90.7);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_39 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(39).call(this.frame_39).wait(1));

	// Layer 7
	this.instance = new lib.Symbol8();
	this.instance.setTransform(71.8,9.3,1.333,1.333,19.9);

	this.instance_1 = new lib.Symbol6();
	this.instance_1.setTransform(1.9,9.8,1.333,1.333);

	this.instance_2 = new lib.Symbol7();
	this.instance_2.setTransform(-65.5,14.9,1.333,1.333,-7.7);

	this.instance_3 = new lib.Symbol5();
	this.instance_3.setTransform(-117.2,23.1,1.333,1.333,-30);

	this.instance_4 = new lib.Symbol9();
	this.instance_4.setTransform(125.3,32,1.333,1.333,30);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4},{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).to({state:[]},1).wait(39));

	// Layer 5
	this.instance_5 = new lib.Symbol8();
	this.instance_5.setTransform(22.1,145.1,1.333,1.333,19.9);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(22).to({_off:false},0).to({x:252.8,y:-100.3},13,cjs.Ease.get(1)).wait(5));

	// Layer 3
	this.instance_6 = new lib.Symbol6();
	this.instance_6.setTransform(3.7,140.7,1.333,1.333);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(17).to({_off:false},0).to({rotation:30,x:199.8,y:-88.8},13,cjs.Ease.get(1)).wait(10));

	// Layer 4
	this.instance_7 = new lib.Symbol7();
	this.instance_7.setTransform(-48.7,139.7,1.333,1.333,-7.7);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(11).to({_off:false},0).to({x:147,y:-94},13,cjs.Ease.get(1)).wait(16));

	// Layer 1
	this.instance_8 = new lib.Symbol5();
	this.instance_8.setTransform(-43.6,155.1,1.333,1.333,-30);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(6).to({_off:false},0).to({x:-132.3,y:-59},13,cjs.Ease.get(1)).wait(21));

	// Layer 6
	this.instance_9 = new lib.Symbol9();
	this.instance_9.setTransform(61.3,142.6,1.333,1.333,30);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(1).to({_off:false},0).to({rotation:65.7,x:305.5,y:-98.4},13,cjs.Ease.get(1)).wait(26));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-183.4,-60.8,375.8,168.2);


(lib.Symbol2 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJPGEQgOgNAAgYIAAgnQAAgXAOgOQANgNAXAAQAWAAAOANQAOAOAAAXIAAAnQAAAYgOANQgOAOgWAAQgXAAgNgOgAJhEiQgFAHAAAPIAAAnQAAAPAFAHQAGAIAMAAQAMAAAFgIQAHgHAAgPIAAgnQAAgPgHgHQgFgIgMAAQgMAAgGAIgAHbGEQgNgNAAgYIAAgnQAAgXANgOQAOgNAXAAQAXAAANANQAOAOAAAXIAAAnQAAAYgOANQgNAOgXAAQgXAAgOgOgAHvEiQgHAHAAAPIAAAnQAAAPAHAHQAFAIAMAAQALAAAGgIQAGgHAAgPIAAgnQAAgPgGgHQgGgIgLAAQgMAAgFAIgAhbGEQgOgNAAgYIAAgnQAAgXAOgOQANgNAXAAQAXAAANANQAOAOAAAXIAAAnQAAAYgOANQgNAOgXAAQgXAAgNgOgAhIEiQgGAHAAAPIAAAnQAAAPAGAHQAGAIALAAQALAAAGgIQAHgHAAgPIAAgnQAAgPgHgHQgGgIgLAAQgLAAgGAIgAj1GHQgPgLABgWIAAgBIAaAAQAAANAFAGQAFAGALAAQAHAAAFgFQAEgFAAgIQAAgIgDgFQgFgFgLgEQgUgHgLgKQgLgJAAgRQAAgRAMgKQAMgKATAAQAUAAAMAKQAMAMAAATIAAABIgaAAQAAgLgFgGQgEgFgJAAQgIAAgEAFQgEAFAAAHQAAAHAFAEQAFAFALAGQATAGALAKQAKAKAAARQAAASgMAJQgMALgTAAQgUAAgNgLgAp/GEQgOgNAAgYIAAgnQAAgXAOgOQANgNAWAAQAXAAAOANQAOAOAAAXIAAAnQAAAYgOANQgOAOgXAAQgWAAgNgOgAptEiQgGAHAAAPIAAAnQAAAPAGAHQAGAIALAAQAMAAAGgIQAGgHAAgPIAAgnQAAgPgGgHQgGgIgMAAQgLAAgGAIgAL2GQIgeg5IgGAAIAAA5IgbAAIAAiIIAbAAIAAA3IAFAAIAdg3IAhAAIgoA+IArBKgAFzGQIAAiIIAbAAIAABzIAzAAIAAAVgADsGQIAAiIIAaAAIAABzIA0AAIAAAVgADFGQIgIgeIgiAAIgIAeIgbAAIAniIIAbAAIAnCIgACgFdIAYAAIgLgrIgBAAgABRGQIgrhXIAAAAIAABXIgbAAIAAiIIAbAAIArBXIAAAAIAAhXIAbAAIAACIgAiXGQIAAiIIAbAAIAACIgAldGQIAAiIIBNAAIAAAUIgyAAIAAAjIApAAIAAAUIgpAAIAAAoIAyAAIAAAVgAm6GQIAAiIIBOAAIAAAUIg0AAIAAAmIAsAAIAAAVIgsAAIAAA5gAoXGQIAAiIIBNAAIAAAUIgzAAIAAAmIArAAIAAAVIgrAAIAAA5gAq1GQQgDgDgBgGIgBgPIAAgKQAAgJgEgGQgFgGgHAAIgQAAIAAA3IgbAAIAAiIIApAAQAUAAAMAKQAMAKAAAUQAAAKgFAIQgFAIgKAEQALAEAFAIQAEAIAAAMIAAALQAAAGACAGQABAGAEADIAAACgAraFEIAOAAQAJAAAEgFQAEgFAAgKQAAgJgEgFQgEgGgJAAIgOAAgAtgGQIAAiIIAuAAQAUAAAMAMQANALAAATQAAAUgNAMQgMANgUAAIgUAAIAAAxgAtGFKIAUAAQAJAAAEgGQAFgHAAgKQAAgKgFgHQgEgGgJAAIgUAAgAMtEaIALg2IAAgmIAtAAIAAAoIgYA0gADWDXQgYgTABgnIAAgBIAuAAQAAAWAJAKQAJAKASAAQAPAAAHgIQAIgJAAgNQAAgPgHgIQgHgJgVgIQgkgMgTgRQgSgQAAgeQAAgeAVgSQAVgRAiAAQAiAAAXARQAUAUgBAiIAAABIgtAAQAAgTgJgJQgJgKgOAAQgOAAgIAJQgGAIAAAOQAAAMAIAHQAJAJAUAJQAjAMARASQASARAAAfQAAAegUASQgVASgjAAQgjAAgYgTgAAfDXQgZgTABgnIAAgBIAuAAQAAAWAJAKQAKAKASAAQAOAAAIgIQAHgJAAgNQAAgPgHgIQgIgJgTgIQgkgMgTgRQgTgQAAgeQAAgeAVgSQAWgRAgAAQAkAAAWARQAVAUgBAiIAAABIgtAAQAAgTgJgJQgJgKgPAAQgNAAgIAJQgHAIAAAOQAAAMAJAHQAIAJAUAJQAjAMASASQARARAAAfQAAAegTASQgVASgjAAQgjAAgYgTgAKSDmIAAjuICHAAIAAAiIhYAAIAAA9IBJAAIAAAlIhJAAIAABGIBYAAIAAAkgAIIDmIhEjuIAxAAIArC7IABAAIAri7IAyAAIhFDugAF+DmIAAjuIAvAAIAADugAiWDmIAAjuICHAAIAAAiIhYAAIAAA9IBKAAIAAAlIhKAAIAABGIBYAAIAAAkgAjhDmQgFgFgCgLIgBgZIAAgRQAAgSgIgKQgHgKgQAAIgbAAIAABgIgvAAIAAjuIBJAAQAjAAAVAQQAVATAAAhQAAASgJAPQgIANgRAIQASAHAJAPQAJAOAAAWIAAASQAAAKACALQACAMAHAEIAAADgAkjBhIAaAAQAOAAAIgJQAIgJAAgRQAAgRgIgJQgHgKgPAAIgaAAgAoPDmIAAjuIBQAAQAlAAAVATQAWAVAAAiQAAAigWAWQgVAVglAAIgiAAIAABXgAnhBqIAiAAQARAAAHgKQAJgNAAgQQAAgSgJgMQgHgLgRAAIgiAAgApjDmIAAiYIAAAAIgsCYIgfAAIgsiXIAAAAIAACXIgvAAIAAjuIA8AAIAtCxIABAAIAuixIA9AAIAADugAteDmIAAjuIAvAAIAADugADPg6QgRgRAAgfIAAgxQAAgfARgRQASgRAdAAQAcAAARARQATARAAAfIAAAxQAAAfgTARQgRASgcAAQgdAAgSgSgADni4QgIAKAAATIAAAxQAAATAIALQAIAJAPAAQAOAAAIgJQAIgLAAgTIAAgxQAAgTgIgKQgIgKgOAAQgPAAgIAKgAhjg2QgSgOABgdIAAAAIAgAAQAAAQAHAHQAHAIANAAQALAAAFgGQAGgHAAgKQAAgKgFgGQgGgGgOgGQgagJgOgMQgNgMAAgWQAAgWAOgNQAQgNAYAAQAaAAAQAOQAPAOgBAYIAAABIghAAQAAgOgGgGQgGgIgLAAQgKAAgGAHQgFAGAAAKQAAAJAGAFQAHAHAPAGQAZAJANANQANAMAAAWQAAAXgPANQgQANgZAAQgZAAgRgOgAmIg5QgRgRAAgeIAAg1QAAgfARgQQAQgQAcAAQAcAAAPANQAPANgBAaIggAAQAAgOgGgGQgGgGgMAAQgNAAgIAJQgHAJAAASIAAA2QAAATAHAJQAIAJAOAAQAJAAAGgCQAGgCADgFIAAgjIgbAAIAAgXIA9AAIAABEQgIAKgOAJQgOAHgWAAQgdAAgRgRgApOg2QgSgOABgdIAAAAIAhAAQAAAQAHAHQAHAIAMAAQALAAAFgGQAGgHAAgKQAAgKgEgGQgGgGgOgGQgbgJgNgMQgOgMAAgWQAAgWAQgNQAPgNAYAAQAZAAAQAOQAQAOgBAYIAAABIghAAQAAgOgHgGQgGgIgLAAQgKAAgFAHQgFAGAAAKQAAAJAGAFQAGAHAPAGQAZAJANANQANAMAAAWQAAAXgPANQgPANgaAAQgZAAgRgOgAL3grIg3hwIgBAAIAABwIgiAAIAAivIAiAAIA3BwIABAAIAAhwIAiAAIAACvgAJrgrIgKgmIgrAAIgKAmIgkAAIAyivIAjAAIAyCvgAI8hsIAeAAIgOg3IgBAAgAGngrQgEgDgBgJIgBgSIAAgMQAAgNgGgIQgFgHgLAAIgUAAIAABGIgiAAIAAivIA0AAQAaAAAQAOQAPANAAAYQAAAOgHAKQgGAKgMAGQANAEAHALQAGALAAAQIAAANQAAAHACAIQABAIAFADIAAADgAF3iMIASAAQALAAAGgGQAGgHAAgMQAAgNgGgGQgFgHgMAAIgSAAgABJgrIAAivIBkAAIAAAbIhCAAIAAAwIA3AAIAAAbIg3AAIAABJgAitgrIg4hwIgBAAIAABwIgiAAIAAivIAiAAIA4BwIABAAIAAhwIAiAAIAACvgAnUgrIAAivIAiAAIAACvgArTgrIAAivIBiAAIAAAbIhAAAIAAAsIA2AAIAAAaIg2AAIAAA0IBAAAIAAAagAtggrIAAivIA3AAQAaAAATAUQARAUAAAhIAAAdQAAAggRAVQgTAUgaAAgAs+hFIAVAAQANAAAHgNQAIgNAAgVIAAgdQAAgVgIgMQgHgNgNAAIgVAAgAG/kHQgPgOAAgaIAAhfIAdAAIAABfQAAAQAGAIQAGAHALAAQALAAAGgHQAGgIAAgQIAAhfIAcAAIAABfQAAAagNAOQgPAOgXAAQgXAAgOgOgAFMkFQgPgLABgYIAAgBIAcAAQAAANAFAHQAGAGALAAQAJAAAEgFQAFgGAAgHQAAgKgEgFQgFgFgMgFQgWgHgLgKQgMgKAAgTQAAgSANgLQANgMAUAAQAWAAANANQANAMAAAUIgcAAQAAgLgGgGQgFgGgJAAQgIAAgFAGQgEAFAAAJQAAAHAFAEQAFAGAMAFQAWAIALAKQAKALAAATQAAASgMALQgNALgVAAQgVAAgPgMgAibkHQgOgOAAgaIAAgrQAAgbANgNQANgPAXAAQAZAAANAMQANAMgBAYIAAAAIgcAAQAAgOgFgGQgFgFgMAAQgKAAgGAHQgFAIAAAQIAAAsQAAAQAGAIQAGAHALAAQALAAAEgFQAFgGAAgOIAbAAIABABQAAAYgMALQgNAMgXAAQgXAAgOgOgAmokHQgOgOAAgaIAAgrQAAgbAOgNQANgPAXAAQAYAAANAMQANAMgBAYIAAAAIgbAAQAAgOgFgGQgFgFgMAAQgLAAgFAHQgFAIAAAQIAAAsQAAAQAFAIQAGAHAMAAQAKAAAFgFQAFgGAAgOIAbAAIAAABQAAAYgMALQgMAMgXAAQgYAAgOgOgAtWkIQgOgOAAgaIAAgqQAAgZAOgPQAOgPAZAAQAYAAAPAPQAPAPAAAZIAAAqQAAAagPAOQgPAPgYAAQgZAAgOgPgAtClyQgGAJAAAPIAAAqQAAAQAGAIQAGAIANAAQAMAAAHgIQAGgIAAgQIAAgqQAAgPgGgJQgHgIgMAAQgNAAgGAIgALFj8IAAiSIBSAAIAAAWIg1AAIAAAlIAtAAIAAAWIgtAAIAAArIA1AAIAAAWgAKSj8IAAhcIAAAAIgaBcIgUAAIgahcIgBAAIAABcIgcAAIAAiSIAlAAIAbBtIABAAIAbhtIAmAAIAACSgADdj8IAAiSIBSAAIAAAWIg1AAIAAAlIAsAAIAAAWIgsAAIAAArIA1AAIAAAWgACvj8QgCgCgCgIIgBgPIAAgKQAAgLgEgGQgFgGgJAAIgRAAIAAA6IgcAAIAAiSIAsAAQAWAAAMALQANALAAAUQAAAMgFAJQgGAIgKAFQALAEAFAJQAGAIAAAOIAAALIABANQABAGAEAEIAAABgACHlNIAQAAQAIAAAGgFQAEgGAAgKQAAgKgEgGQgFgGgJAAIgQAAgAAOj8Igeg9IgIAAIAAA9IgcAAIAAiSIAcAAIAAA8IAGAAIAdg8IAjAAIgqBDIAuBPgAjbj8IAAiSIAdAAIAACSgAlBj8IAAiSIAdAAIAAB8IA3AAIAAAWgApnj8IAAiSIBTAAIAAAWIg3AAIAAAlIAuAAIAAAWIguAAIAAArIA3AAIAAAWgAqaj8IgvhdIAAAAIAABdIgdAAIAAiSIAdAAIAvBeIAAheIAcAAIAACSgAoAkvIAAgXIAzAAIAAAXg");
	this.shape.setTransform(2.5,-0.5);

	// Layer 1
	this.instance = new lib.Symbol3();

	this.addChild(this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-364,-45,728,90);


(lib.Symbol40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_696 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(696).call(this.frame_696).wait(1));

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AkABdQgWgRAAgjIAAgBIAqAAQAAAUAIAJQAIAJAQAAQANAAAHgHQAGgIAAgMQAAgNgFgIQgIgHgRgHQgggLgRgNQgQgPAAgbQgBgaAUgQQASgRAeAAQAfAAAUARQASASAAAeIAAABIgpAAQAAgRgIgIQgIgJgNAAQgMAAgHAIQgGAIAAAMQAAAKAHAHQAIAIASAIQAgALAPAOQAQAPAAAbQAAAbgSAQQgTAQgfAAQgfAAgVgRgAsYBZQgVgUAAglIAAg/QAAgmAUgUQAUgUAiAAQAkAAASARQARAQAAAfIgBAAIgnAAQABgQgIgIQgHgHgQAAQgPAAgKALQgIALgBAWIAABAQABAXAIALQAKALARAAQAMAAAGgDQAHgCAFgFIAAgrIghAAIAAgbIBKAAIAABSQgJAMgSAKQgRAJgbAAQgjAAgVgVgAKfBrIAAjVIBCAAQAiAAAWAZQAVAZABAnIAAAiQgBAogVAZQgWAZgiAAgALIBKIAZAAQAQAAAKgQQAKgPAAgaIAAgiQAAgZgKgPQgKgQgQAAIgZAAgAINBrIAAjVIB4AAIAAAhIhPAAIAAA2IBBAAIAAAfIhBAAIAAA+IBPAAIAAAhgAGbBrIAAi0IgwAAIAAghICNAAIAAAhIgyAAIAAC0gAE0BrQgFgFgBgKIgBgWIAAgPQAAgQgHgJQgHgJgNAAIgZAAIAABWIgqAAIAAjVIBBAAQAfAAATARQASAQAAAeQAAAQgHANQgIAMgOAFQAQAGAHANQAIANAAAUIAAAQQAAAJADAJQABAKAGAFIAAADgAD5gKIAXAAQAMAAAJgIQAGgIAAgPQAAgPgGgIQgIgJgNAAIgXAAgACTBrIgNgvIg2AAIgLAvIgsAAIA9jVIArAAIA9DVgABZAbIAlAAIgShCIgBAAgAhIBrIAAi0IgxAAIAAghICLAAIAAAhIgwAAIAAC0gAnDBrIAAi0IgyAAIAAghICOAAIAAAhIgyAAIAAC0gAp7BrIAAjVIB5AAIAAAhIhQAAIAAA2IBCAAIAAAfIhCAAIAAA+IBQAAIAAAhg");
	this.shape.setTransform(-20,-0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(697));

	// Layer 3
	this.instance = new lib.Symbol44();
	this.instance.setTransform(86.1,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).to({x:79.7},14,cjs.Ease.get(-1)).to({x:86.1},15,cjs.Ease.get(-1)).wait(1));

	// Layer 1
	this.instance_1 = new lib.Symbol42();

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(697));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110.5,-22.1,219.3,44.2);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_99 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(99).call(this.frame_99).wait(1));

	// Layer 2
	this.instance = new lib.Symbol18();
	this.instance.setTransform(152.4,189.2);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).to({x:62.8,y:100},10).wait(2).to({y:106},3).wait(2).to({y:112},3).wait(2).to({y:118.6},3).wait(2).to({y:124.6},3).wait(2).to({x:94.2,y:100.4},8).wait(2).to({y:106.4},3).wait(2).to({y:112.4},3).wait(2).to({y:118.4},3).wait(2).to({y:124.4},3).wait(2).to({x:126.8,y:100.4},8).wait(2).to({y:106.4},3).wait(2).to({y:112.4},3).wait(2).to({y:118.4},4).wait(2).to({y:124.4},4).wait(4));

	// Layer 13
	this.instance_1 = new lib.Symbol23();
	this.instance_1.setTransform(27.6,29.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(96).to({_off:false},0).wait(4));

	// Layer 14
	this.instance_2 = new lib.Symbol23();
	this.instance_2.setTransform(27.6,23.6);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(90).to({_off:false},0).wait(10));

	// Layer 15
	this.instance_3 = new lib.Symbol23();
	this.instance_3.setTransform(27.6,17.6);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(84).to({_off:false},0).wait(16));

	// Layer 16
	this.instance_4 = new lib.Symbol23();
	this.instance_4.setTransform(27.6,11.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(79).to({_off:false},0).wait(21));

	// Layer 17
	this.instance_5 = new lib.Symbol23();
	this.instance_5.setTransform(27.6,5.6);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(74).to({_off:false},0).wait(26));

	// Layer 8
	this.instance_6 = new lib.Symbol23();
	this.instance_6.setTransform(-4.4,29.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(64).to({_off:false},0).wait(36));

	// Layer 9
	this.instance_7 = new lib.Symbol23();
	this.instance_7.setTransform(-4.4,23.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(59).to({_off:false},0).wait(41));

	// Layer 10
	this.instance_8 = new lib.Symbol23();
	this.instance_8.setTransform(-4.4,17.6);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(54).to({_off:false},0).wait(46));

	// Layer 11
	this.instance_9 = new lib.Symbol23();
	this.instance_9.setTransform(-4.4,11.6);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(49).to({_off:false},0).wait(51));

	// Layer 12
	this.instance_10 = new lib.Symbol23();
	this.instance_10.setTransform(-4.4,5.6);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(44).to({_off:false},0).wait(56));

	// Layer 7
	this.instance_11 = new lib.Symbol23();
	this.instance_11.setTransform(-36.4,29.6);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(34).to({_off:false},0).wait(66));

	// Layer 6
	this.instance_12 = new lib.Symbol23();
	this.instance_12.setTransform(-36.4,23.6);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(29).to({_off:false},0).wait(71));

	// Layer 5
	this.instance_13 = new lib.Symbol23();
	this.instance_13.setTransform(-36.4,17.6);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(24).to({_off:false},0).wait(76));

	// Layer 4
	this.instance_14 = new lib.Symbol23();
	this.instance_14.setTransform(-36.4,11.6);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(19).to({_off:false},0).wait(81));

	// Layer 3
	this.instance_15 = new lib.Symbol23();
	this.instance_15.setTransform(-36.4,5.6);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(14).to({_off:false},0).wait(86));

	// Layer 1
	this.instance_16 = new lib.Symbol22();

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(100));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.8,-82.8,120.9,168.9);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_59 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(59).call(this.frame_59).wait(1));

	// Layer 5
	this.instance = new lib.Symbol2();
	this.instance.setTransform(-2.4,57.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(59));

	// Layer 9
	this.instance_1 = new lib.Symbol4();
	this.instance_1.setTransform(-4.7,163.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(34).to({_off:false},0).wait(26));

	// Layer 7 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_29 = new cjs.Graphics().p("Eg42gHBIAAuEMBxuAAAIAAOEg");
	var mask_graphics_30 = new cjs.Graphics().p("Eg42gC0IAAuEMBxuAAAIAAOEg");
	var mask_graphics_31 = new cjs.Graphics().p("Eg42AA6IAAuCMBxuAAAIAAOCg");
	var mask_graphics_32 = new cjs.Graphics().p("Eg42AEPIAAuCMBxuAAAIAAOCg");
	var mask_graphics_33 = new cjs.Graphics().p("Eg42AHBIAAuCMBxuAAAIAAOCg");
	var mask_graphics_34 = new cjs.Graphics().p("Eg42AHCIAAuCMBxuAAAIAAOCg");
	var mask_graphics_35 = new cjs.Graphics().p("Eg42AHCIAAuCMBxuAAAIAAOCg");
	var mask_graphics_36 = new cjs.Graphics().p("Eg42AHBIAAuCMBxuAAAIAAOCg");
	var mask_graphics_37 = new cjs.Graphics().p("Eg42AHKIAAuCMBxuAAAIAAOCg");
	var mask_graphics_38 = new cjs.Graphics().p("Eg42AH0IAAuCMBxuAAAIAAOCg");
	var mask_graphics_39 = new cjs.Graphics().p("Eg42AICIAAuCMBxuAAAIAAOCg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(29).to({graphics:mask_graphics_29,x:-2.4,y:-135.1}).wait(1).to({graphics:mask_graphics_30,x:-2.4,y:-108.2}).wait(1).to({graphics:mask_graphics_31,x:-2.4,y:-84.1}).wait(1).to({graphics:mask_graphics_32,x:-2.4,y:-62.9}).wait(1).to({graphics:mask_graphics_33,x:-2.4,y:-44}).wait(1).to({graphics:mask_graphics_34,x:-2.4,y:-12.8}).wait(1).to({graphics:mask_graphics_35,x:-2.4,y:12.7}).wait(1).to({graphics:mask_graphics_36,x:-2.4,y:32.5}).wait(1).to({graphics:mask_graphics_37,x:-2.4,y:45.8}).wait(1).to({graphics:mask_graphics_38,x:-2.4,y:50.1}).wait(1).to({graphics:mask_graphics_39,x:-2.4,y:51.5}).wait(21));

	// Layer 8
	this.instance_2 = new lib.Symbol2();
	this.instance_2.setTransform(-2.4,57.6);
	this.instance_2._off = true;

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(29).to({_off:false},0).wait(31));

	// Layer 4
	this.instance_3 = new lib.Symbol14();
	this.instance_3.setTransform(0.1,67.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(10).to({_off:false},0).to({y:35.5,alpha:1},7).to({y:43.5},6).wait(37));

	// Layer 3
	this.instance_4 = new lib.Symbol13();
	this.instance_4.setTransform(0.3,38.4);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(7).to({_off:false},0).to({y:6.4,alpha:1},7).to({y:14.4},6).wait(40));

	// Layer 2
	this.instance_5 = new lib.Symbol12();
	this.instance_5.setTransform(0.2,6.2);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(4).to({_off:false},0).to({y:-25.8,alpha:1},7).to({y:-18.2},6).wait(43));

	// Layer 1
	this.instance_6 = new lib.Symbol11();
	this.instance_6.setTransform(0,-17);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({_off:false},0).to({y:-49,alpha:1},7).to({y:-42.6},6).wait(46));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-366.4,12.6,728,90);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_369 = function() {
		if(!this.loops_played)
		this.loops_played = 1;
		
		if(this.loops_played >= 2) 
			this.gotoAndStop(); 
			else play();
	}
	this.frame_479 = function() {
		this.loops_played++;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(369).call(this.frame_369).wait(110).call(this.frame_479).wait(1));

	// Layer 6
	this.instance = new lib.Symbol41();
	this.instance.setTransform(80,0);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(359).to({_off:false},0).wait(110).to({x:79.7,y:0.3},0).to({alpha:0},9,cjs.Ease.get(1)).to({_off:true},1).wait(1));

	// Layer 7
	this.instance_1 = new lib.Symbol40();
	this.instance_1.setTransform(-271.8,20.5,0.626,0.626);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(480));

	// Layer 8
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#17AABD").s().p("AtKB5IAAgQICSAAIAAAQgAMgBuIAAh0IgXAAIAAgOIAXAAIAAgyIARAAIAAAyIAaAAIAAAOIgaAAIAAB0gALLBuIAAh0IgRAAIAAgOIARAAIAAgVQAAgOADgHQACgFAGgEQAHgEAJABQAIAAALACIAAARQgJgDgHAAQgFAAgDACQgDABgBADQgBACAAAMIAAASIAcAAIAAAOIgcAAIAAB0gAKOBuIAAiCIARAAIAACCgAIgBuIAAixIASAAIAACgIBGAAIAAARgAsdBLIAAgPIBlAAIAAAPgAp8gNIgoAAIAAgRICyAAIAAgIIiyAAIAAgWICAAAIAAgHIiAAAIAAgXIBtAAIAAgIIhtAAIAAgVICUAAIAAA7IA8AAIAAAvIgmAAIhBBHgAs9AcIAAgPICFAAIAAAPgAKNgzQgEgEAAgGQAAgFAEgFQAEgDAGAAQAGAAADADQAFAFAAAFQAAAGgFAEQgDAEgGABQgGgBgEgEg");
	this.shape.setTransform(-271.8,-21.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#EF851F").s().p("AovCLIAAglIAjAAIAAgPIgjAAIAAgfIBQAAIAAgPIhQAAIAAgfIAwAAIAAgOIgwAAIAAgcIAUAAIAoAAIBBBHIBBhHIAmAAIASAAIAACrgAITBLQgTgTAAgeQAAgcATgUQAUgUAeAAQAeAAAUAUQATAUABAeIAAAGIhrAAQABAOALAJQALAIAPAAQASAAANgNIAdANQgLAQgOAGQgPAHgUAAQgfAAgUgTgAItgGQgGAFgFAKIBIAAQgEgKgKgGQgJgHgNAAQgOAAgLAIgACdBVQgNgKgGgRQgEgNAAgfIAAg1IAiAAIAAA9QAAASACAIQADAHAFAFQAHADAIAAQAHAAAGgDQAGgEADgIQACgGAAgSIAAg/IAhAAIAAA2QAAAjgFAMQgGAQgOAIQgMAIgVAAQgWAAgNgJgAAOBIIAUgWQAGAHAIADQAIAFAGAAQAGAAAEgDQAFgDAAgFQAAgHgPgIIgLgFQghgRAAgWQAAgPANgLQAMgLASAAQAOAAALAFQAMAHAHAKIgUAUQgNgMgKAAQgGAAgDACQgDACAAAEQAAADACABQABABAJAEIANAGQASAJAIAKQAGAKAAANQAAASgMAMQgNALgWAAQgdAAgRgWgAh4BLQgUgUABgdQgBgcAUgUQATgUAeAAQAeAAAVAUQATAUAAAeIAAAGIhqAAQACAOAJAJQALAIAPAAQATAAANgNIAcANQgKAPgPAHQgOAHgVAAQgfAAgTgTgAhegGQgGAEgGALIBIAAQgDgKgKgGQgJgHgOAAQgOAAgKAIgAHGBbIAAhDQAAgWgGgGQgGgIgMAAQgHAAgIAFQgHAFgDAGQgDAIAAAUIAAA7IghAAIAAhAQAAgRgDgIQgDgGgFgEQgGgEgGAAQgJAAgHAFQgGAFgEAHQgEAJAAATIAAA6IghAAIAAiCIAhAAIAAAPQAKgKAKgEQAKgEAMAAQANAAAKAGQAKAGAGAMQAIgMALgGQAMgGANAAQAOAAALAGQAMAHAEAKQAFAKgBAXIAABNgAjDBbIgohMIgDAAIAABMIgiAAIAAixIAkAAQAeAAANAFQAMAGAIAMQAIANAAAQQAAASgJAMQgIAKgRAGIAqBPgAjugQIALAAQAQAAAGgEQAHgFgBgJQAAgGgCgEQgEgFgEgCQgHgCgMAAIgKAAgApjgxIAAgIIBIAAIAAAIgAmHhOIAAg8IA8A8gAp3hOIAAgIIBcAAIAAAIgAqJhsIAAgIIBuAAIAAAIg");
	this.shape_1.setTransform(-285.5,-20);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(480));

	// Layer 10
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#F0F0F0","rgba(240,240,240,0)"],[0.753,0.945],-119.7,0,119.8,0).s().p("A0SHCIAAuDMAolAAAIAAODg");
	this.shape_2.setTransform(-234,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(480));

	// Layer 2
	this.instance_2 = new lib.Symbol19();
	this.instance_2.setTransform(-48.1,0,4.061,4.061);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(239).to({_off:false},0).to({scaleX:0.97,scaleY:0.97,x:-48},11).to({scaleX:0.76,scaleY:0.76},109,cjs.Ease.get(1)).to({scaleX:0.28,scaleY:0.28,alpha:0},5).to({_off:true},1).wait(115));

	// Layer 5
	this.instance_3 = new lib.Symbol21();
	this.instance_3.setTransform(209.2,134.3,0.869,0.869,-30);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(239).to({_off:false},0).to({x:123.6,y:2.8},11,cjs.Ease.get(1)).wait(104).to({x:209.2,y:134.3},10,cjs.Ease.get(1)).to({_off:true},1).wait(115));

	// Layer 11
	this.instance_4 = new lib.Symbol25();
	this.instance_4.setTransform(-98,343.9);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(120).to({_off:false},0).to({y:193.9},10).wait(106).to({y:343.9},7,cjs.Ease.get(1)).to({_off:true},1).wait(236));

	// Layer 4
	this.instance_5 = new lib.Symbol31();
	this.instance_5.setTransform(-24.8,0.7,0.754,0.754);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(120).to({_off:false},0).wait(116).to({alpha:0},7).to({_off:true},1).wait(236));

	// Layer 3
	this.instance_6 = new lib.Symbol10();
	this.instance_6.setTransform(2.4,-57.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({_off:true},140).wait(340));

	// Layer 1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F0F0F0").s().p("Eg42AHCIAAuDMBxtAAAIAAODg");

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(480));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-364,-45,728,90.1);


// stage content:
(lib.BanResumeLift_728x90_101215_final = function() {
	this.initialize();

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#333333").ss(1,1,1).p("Eg40gG+MBxpAAAIAAN9MhxpAAAg");
	this.shape.setTransform(364,45);

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Eg43AHCIAAuDMBxvAAAIAAODg");
	mask.setTransform(364,45);

	// banner
	this.instance = new lib.Symbol1();
	this.instance.setTransform(364,45.1);

	this.instance.mask = mask;

	// back
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_1.setTransform(364,45);

	this.shape_1.mask = mask;

	this.addChild(this.shape_1,this.instance,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(363.3,44.3,729.5,91.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;